limit.maxIDLength:
  - value: 255
    constraints: {}
system.forceSearchAttributesCacheRefreshOnRead:
  - value: true # Local stand only: makes new search attributes visible immediately.
    constraints: {}
