// Command benchreport turns `go test -bench` output of the optimizer core into a Markdown report.
package main

import (
	"bufio"
	"errors"
	"flag"
	"fmt"
	"io"
	"maps"
	"os"
	"regexp"
	"slices"
	"strconv"
	"strings"
)

type result struct {
	Name                                   string
	Runs, Iters                            int
	NsOp, P50, P95, P99, BytesOp, AllocsOp float64
}

var (
	procSuffix = regexp.MustCompile(`-\d+$`)
	units      = []string{"ns/op", "p50-ms", "p95-ms", "p99-ms", "B/op", "allocs/op"}
)

// parse keeps the median of repeated runs, which a single slow run cannot drag.
func parse(r io.Reader) ([]result, error) {
	samples := map[string]map[string][]float64{}
	var order []string
	scan := bufio.NewScanner(r)
	for scan.Scan() {
		line := scan.Text()
		if strings.HasPrefix(line, "--- FAIL") || strings.HasPrefix(line, "FAIL") {
			return nil, errors.New("benchmark run failed: " + line)
		}
		fields := strings.Fields(line)
		if len(fields) < 4 || !strings.HasPrefix(fields[0], "Benchmark") {
			continue
		}
		name := procSuffix.ReplaceAllString(fields[0], "")
		if samples[name] == nil {
			samples[name] = map[string][]float64{}
			order = append(order, name)
		}
		iters, err := strconv.ParseFloat(fields[1], 64)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", name, err)
		}
		samples[name]["iters"] = append(samples[name]["iters"], iters)
		for i := 2; i+1 < len(fields); i += 2 {
			v, err := strconv.ParseFloat(fields[i], 64)
			if err != nil {
				return nil, fmt.Errorf("%s: %w", name, err)
			}
			samples[name][fields[i+1]] = append(samples[name][fields[i+1]], v)
		}
	}
	if err := scan.Err(); err != nil {
		return nil, err
	}
	if len(order) == 0 {
		return nil, errors.New("no benchmark results")
	}
	out := make([]result, 0, len(order))
	for _, name := range order {
		m := samples[name]
		for _, unit := range units {
			if len(m[unit]) == 0 {
				return nil, fmt.Errorf("%s: no %s", name, unit)
			}
		}
		out = append(out, result{
			Name: name, Runs: len(m["ns/op"]), Iters: int(median(m["iters"])), NsOp: median(m["ns/op"]),
			P50: median(m["p50-ms"]), P95: median(m["p95-ms"]), P99: median(m["p99-ms"]),
			BytesOp: median(m["B/op"]), AllocsOp: median(m["allocs/op"]),
		})
	}
	return out, nil
}

func median(v []float64) float64 {
	s := slices.Sorted(slices.Values(v))
	return s[len(s)/2]
}

func render(w io.Writer, env map[string]string, results []result, cpuTop, memTop string) error {
	var b strings.Builder
	b.WriteString("# Optimizer core benchmarks\n\n")
	b.WriteString("Generated by `make bench-optimizer`. The numbers describe one machine and one run; they are measurements, not guarantees.\n\n")
	b.WriteString("## Environment\n\n")
	for _, k := range slices.Sorted(maps.Keys(env)) {
		fmt.Fprintf(&b, "- %s: %s\n", k, env[k])
	}
	b.WriteString("\n## What is measured\n\n")
	b.WriteString("One in-process call with the candidate pool already in memory and straight-line travel estimates. " +
		"gRPC, protobuf mapping, PostgreSQL, the routing engine, Redis, the network and text embedding are outside the measurement. " +
		"Pools are synthetic and fixed, so runs are comparable. Each row is the median over the repeated runs. " +
		"Percentiles are taken over the iterations of one run, so with few iterations p95 and p99 both fall on the slowest one.\n\n")
	b.WriteString("## Results\n\n")
	b.WriteString("| Benchmark | Runs | iterations/run | mean ms | p50 ms | p95 ms | p99 ms | B/op | allocs/op |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		fmt.Fprintf(&b, "| %s | %d | %d | %.3f | %.3f | %.3f | %.3f | %.0f | %.0f |\n", r.Name, r.Runs, r.Iters, r.NsOp/1e6, r.P50, r.P95, r.P99, r.BytesOp, r.AllocsOp)
	}
	fmt.Fprintf(&b, "\n## CPU profile, top functions\n\n```\n%s\n```\n", strings.TrimSpace(cpuTop))
	fmt.Fprintf(&b, "\n## Allocation profile, top functions\n\n```\n%s\n```\n", strings.TrimSpace(memTop))
	_, err := io.WriteString(w, b.String())
	return err
}

type envFlags map[string]string

func (e envFlags) String() string { return "" }

func (e envFlags) Set(v string) error {
	k, val, ok := strings.Cut(v, "=")
	if !ok {
		return errors.New("env must be key=value")
	}
	e[k] = val
	return nil
}

func main() {
	env := envFlags{}
	bench := flag.String("bench", "", "go test -bench output")
	cpu := flag.String("cpu-top", "", "go tool pprof -top output for CPU")
	mem := flag.String("mem-top", "", "go tool pprof -top output for allocations")
	flag.Var(env, "env", "key=value line for the environment section, repeatable")
	flag.Parse()
	if err := run(*bench, *cpu, *mem, env, os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(bench, cpu, mem string, env map[string]string, w io.Writer) error {
	f, err := os.Open(bench)
	if err != nil {
		return err
	}
	defer f.Close()
	results, err := parse(f)
	if err != nil {
		return err
	}
	cpuTop, err := os.ReadFile(cpu)
	if err != nil {
		return err
	}
	memTop, err := os.ReadFile(mem)
	if err != nil {
		return err
	}
	return render(w, env, results, string(cpuTop), string(memTop))
}
