// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: optimizer/v1/constraints.proto

package optimizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BudgetMode int32

const (
	BudgetMode_BUDGET_MODE_UNSPECIFIED BudgetMode = 0
	BudgetMode_BUDGET_MODE_NONE        BudgetMode = 1
	BudgetMode_BUDGET_MODE_ADVISORY    BudgetMode = 2
	// Satisfied only when the upper bound of every price is known.
	BudgetMode_BUDGET_MODE_STRICT BudgetMode = 3
)

// Enum value maps for BudgetMode.
var (
	BudgetMode_name = map[int32]string{
		0: "BUDGET_MODE_UNSPECIFIED",
		1: "BUDGET_MODE_NONE",
		2: "BUDGET_MODE_ADVISORY",
		3: "BUDGET_MODE_STRICT",
	}
	BudgetMode_value = map[string]int32{
		"BUDGET_MODE_UNSPECIFIED": 0,
		"BUDGET_MODE_NONE":        1,
		"BUDGET_MODE_ADVISORY":    2,
		"BUDGET_MODE_STRICT":      3,
	}
)

func (x BudgetMode) Enum() *BudgetMode {
	p := new(BudgetMode)
	*p = x
	return p
}

func (x BudgetMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetMode) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_constraints_proto_enumTypes[0].Descriptor()
}

func (BudgetMode) Type() protoreflect.EnumType {
	return &file_optimizer_v1_constraints_proto_enumTypes[0]
}

func (x BudgetMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetMode.Descriptor instead.
func (BudgetMode) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_constraints_proto_rawDescGZIP(), []int{0}
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          BudgetMode             `protobuf:"varint,1,opt,name=mode,proto3,enum=optimizer.v1.BudgetMode" json:"mode,omitempty"`
	Limit         *Money                 `protobuf:"bytes,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_optimizer_v1_constraints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_constraints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_constraints_proto_rawDescGZIP(), []int{0}
}

func (x *Budget) GetMode() BudgetMode {
	if x != nil {
		return x.Mode
	}
	return BudgetMode_BUDGET_MODE_UNSPECIFIED
}

func (x *Budget) GetLimit() *Money {
	if x != nil {
		return x.Limit
	}
	return nil
}

// The balance is always user-reported and never confirms a benefit by itself.
type ProgramBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Program       string                 `protobuf:"bytes,1,opt,name=program,proto3" json:"program,omitempty"`
	Balance       *Money                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramBalance) Reset() {
	*x = ProgramBalance{}
	mi := &file_optimizer_v1_constraints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramBalance) ProtoMessage() {}

func (x *ProgramBalance) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_constraints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramBalance.ProtoReflect.Descriptor instead.
func (*ProgramBalance) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_constraints_proto_rawDescGZIP(), []int{1}
}

func (x *ProgramBalance) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *ProgramBalance) GetBalance() *Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

type RouteObligation struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	VisitId              []byte                 `protobuf:"bytes,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	SessionId            []byte                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	StartsAt             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	ArrivalBufferSeconds int64                  `protobuf:"varint,4,opt,name=arrival_buffer_seconds,json=arrivalBufferSeconds,proto3" json:"arrival_buffer_seconds,omitempty"`
	Participation        ParticipationStatus    `protobuf:"varint,5,opt,name=participation,proto3,enum=optimizer.v1.ParticipationStatus" json:"participation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RouteObligation) Reset() {
	*x = RouteObligation{}
	mi := &file_optimizer_v1_constraints_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteObligation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteObligation) ProtoMessage() {}

func (x *RouteObligation) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_constraints_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteObligation.ProtoReflect.Descriptor instead.
func (*RouteObligation) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_constraints_proto_rawDescGZIP(), []int{2}
}

func (x *RouteObligation) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *RouteObligation) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RouteObligation) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *RouteObligation) GetArrivalBufferSeconds() int64 {
	if x != nil {
		return x.ArrivalBufferSeconds
	}
	return 0
}

func (x *RouteObligation) GetParticipation() ParticipationStatus {
	if x != nil {
		return x.Participation
	}
	return ParticipationStatus_PARTICIPATION_STATUS_UNSPECIFIED
}

type LunchWindow struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StartAt            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt              *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	MinDurationSeconds int64                  `protobuf:"varint,3,opt,name=min_duration_seconds,json=minDurationSeconds,proto3" json:"min_duration_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LunchWindow) Reset() {
	*x = LunchWindow{}
	mi := &file_optimizer_v1_constraints_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LunchWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunchWindow) ProtoMessage() {}

func (x *LunchWindow) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_constraints_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunchWindow.ProtoReflect.Descriptor instead.
func (*LunchWindow) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_constraints_proto_rawDescGZIP(), []int{3}
}

func (x *LunchWindow) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *LunchWindow) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *LunchWindow) GetMinDurationSeconds() int64 {
	if x != nil {
		return x.MinDurationSeconds
	}
	return 0
}

// User-confirmed input. Movement modes, load profile, programs and audiences are open code lists.
type RouteConstraints struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InterestMask       uint64                 `protobuf:"varint,1,opt,name=interest_mask,json=interestMask,proto3" json:"interest_mask,omitempty"`
	ExcludedCategories []Category             `protobuf:"varint,2,rep,packed,name=excluded_categories,json=excludedCategories,proto3,enum=optimizer.v1.Category" json:"excluded_categories,omitempty"`
	MovementModes      []string               `protobuf:"bytes,3,rep,name=movement_modes,json=movementModes,proto3" json:"movement_modes,omitempty"`
	LoadProfile        string                 `protobuf:"bytes,4,opt,name=load_profile,json=loadProfile,proto3" json:"load_profile,omitempty"`
	Budget             *Budget                `protobuf:"bytes,5,opt,name=budget,proto3" json:"budget,omitempty"`
	BenefitPrograms    []string               `protobuf:"bytes,6,rep,name=benefit_programs,json=benefitPrograms,proto3" json:"benefit_programs,omitempty"`
	ProgramBalance     *ProgramBalance        `protobuf:"bytes,7,opt,name=program_balance,json=programBalance,proto3" json:"program_balance,omitempty"`
	// User-reported audience claims such as student or senior.
	AudienceClaims   []string           `protobuf:"bytes,8,rep,name=audience_claims,json=audienceClaims,proto3" json:"audience_claims,omitempty"`
	Obligations      []*RouteObligation `protobuf:"bytes,9,rep,name=obligations,proto3" json:"obligations,omitempty"`
	SoftPreferences  []string           `protobuf:"bytes,10,rep,name=soft_preferences,json=softPreferences,proto3" json:"soft_preferences,omitempty"`
	LunchWindow      *LunchWindow       `protobuf:"bytes,11,opt,name=lunch_window,json=lunchWindow,proto3" json:"lunch_window,omitempty"`
	AcceptedUnknowns []string           `protobuf:"bytes,12,rep,name=accepted_unknowns,json=acceptedUnknowns,proto3" json:"accepted_unknowns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteConstraints) Reset() {
	*x = RouteConstraints{}
	mi := &file_optimizer_v1_constraints_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteConstraints) ProtoMessage() {}

func (x *RouteConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_constraints_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteConstraints.ProtoReflect.Descriptor instead.
func (*RouteConstraints) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_constraints_proto_rawDescGZIP(), []int{4}
}

func (x *RouteConstraints) GetInterestMask() uint64 {
	if x != nil {
		return x.InterestMask
	}
	return 0
}

func (x *RouteConstraints) GetExcludedCategories() []Category {
	if x != nil {
		return x.ExcludedCategories
	}
	return nil
}

func (x *RouteConstraints) GetMovementModes() []string {
	if x != nil {
		return x.MovementModes
	}
	return nil
}

func (x *RouteConstraints) GetLoadProfile() string {
	if x != nil {
		return x.LoadProfile
	}
	return ""
}

func (x *RouteConstraints) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *RouteConstraints) GetBenefitPrograms() []string {
	if x != nil {
		return x.BenefitPrograms
	}
	return nil
}

func (x *RouteConstraints) GetProgramBalance() *ProgramBalance {
	if x != nil {
		return x.ProgramBalance
	}
	return nil
}

func (x *RouteConstraints) GetAudienceClaims() []string {
	if x != nil {
		return x.AudienceClaims
	}
	return nil
}

func (x *RouteConstraints) GetObligations() []*RouteObligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}

func (x *RouteConstraints) GetSoftPreferences() []string {
	if x != nil {
		return x.SoftPreferences
	}
	return nil
}

func (x *RouteConstraints) GetLunchWindow() *LunchWindow {
	if x != nil {
		return x.LunchWindow
	}
	return nil
}

func (x *RouteConstraints) GetAcceptedUnknowns() []string {
	if x != nil {
		return x.AcceptedUnknowns
	}
	return nil
}

var File_optimizer_v1_constraints_proto protoreflect.FileDescriptor

const file_optimizer_v1_constraints_proto_rawDesc = "" +
	"\n" +
	"\x1eoptimizer/v1/constraints.proto\x12\foptimizer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19optimizer/v1/values.proto\"a\n" +
	"\x06Budget\x12,\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x18.optimizer.v1.BudgetModeR\x04mode\x12)\n" +
	"\x05limit\x18\x02 \x01(\v2\x13.optimizer.v1.MoneyR\x05limit\"Y\n" +
	"\x0eProgramBalance\x12\x18\n" +
	"\aprogram\x18\x01 \x01(\tR\aprogram\x12-\n" +
	"\abalance\x18\x02 \x01(\v2\x13.optimizer.v1.MoneyR\abalance\"\x83\x02\n" +
	"\x0fRouteObligation\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\fR\avisitId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\fR\tsessionId\x127\n" +
	"\tstarts_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x124\n" +
	"\x16arrival_buffer_seconds\x18\x04 \x01(\x03R\x14arrivalBufferSeconds\x12G\n" +
	"\rparticipation\x18\x05 \x01(\x0e2!.optimizer.v1.ParticipationStatusR\rparticipation\"\xa9\x01\n" +
	"\vLunchWindow\x125\n" +
	"\bstart_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x120\n" +
	"\x14min_duration_seconds\x18\x03 \x01(\x03R\x12minDurationSeconds\"\xea\x04\n" +
	"\x10RouteConstraints\x12#\n" +
	"\rinterest_mask\x18\x01 \x01(\x04R\finterestMask\x12G\n" +
	"\x13excluded_categories\x18\x02 \x03(\x0e2\x16.optimizer.v1.CategoryR\x12excludedCategories\x12%\n" +
	"\x0emovement_modes\x18\x03 \x03(\tR\rmovementModes\x12!\n" +
	"\fload_profile\x18\x04 \x01(\tR\vloadProfile\x12,\n" +
	"\x06budget\x18\x05 \x01(\v2\x14.optimizer.v1.BudgetR\x06budget\x12)\n" +
	"\x10benefit_programs\x18\x06 \x03(\tR\x0fbenefitPrograms\x12E\n" +
	"\x0fprogram_balance\x18\a \x01(\v2\x1c.optimizer.v1.ProgramBalanceR\x0eprogramBalance\x12'\n" +
	"\x0faudience_claims\x18\b \x03(\tR\x0eaudienceClaims\x12?\n" +
	"\vobligations\x18\t \x03(\v2\x1d.optimizer.v1.RouteObligationR\vobligations\x12)\n" +
	"\x10soft_preferences\x18\n" +
	" \x03(\tR\x0fsoftPreferences\x12<\n" +
	"\flunch_window\x18\v \x01(\v2\x19.optimizer.v1.LunchWindowR\vlunchWindow\x12+\n" +
	"\x11accepted_unknowns\x18\f \x03(\tR\x10acceptedUnknowns*q\n" +
	"\n" +
	"BudgetMode\x12\x1b\n" +
	"\x17BUDGET_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BUDGET_MODE_NONE\x10\x01\x12\x18\n" +
	"\x14BUDGET_MODE_ADVISORY\x10\x02\x12\x16\n" +
	"\x12BUDGET_MODE_STRICT\x10\x03BBZ@github.com/andres1m/impuls-goroda/proto/optimizer/v1;optimizerv1b\x06proto3"

var (
	file_optimizer_v1_constraints_proto_rawDescOnce sync.Once
	file_optimizer_v1_constraints_proto_rawDescData []byte
)

func file_optimizer_v1_constraints_proto_rawDescGZIP() []byte {
	file_optimizer_v1_constraints_proto_rawDescOnce.Do(func() {
		file_optimizer_v1_constraints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_v1_constraints_proto_rawDesc), len(file_optimizer_v1_constraints_proto_rawDesc)))
	})
	return file_optimizer_v1_constraints_proto_rawDescData
}

var file_optimizer_v1_constraints_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_optimizer_v1_constraints_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_optimizer_v1_constraints_proto_goTypes = []any{
	(BudgetMode)(0),               // 0: optimizer.v1.BudgetMode
	(*Budget)(nil),                // 1: optimizer.v1.Budget
	(*ProgramBalance)(nil),        // 2: optimizer.v1.ProgramBalance
	(*RouteObligation)(nil),       // 3: optimizer.v1.RouteObligation
	(*LunchWindow)(nil),           // 4: optimizer.v1.LunchWindow
	(*RouteConstraints)(nil),      // 5: optimizer.v1.RouteConstraints
	(*Money)(nil),                 // 6: optimizer.v1.Money
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(ParticipationStatus)(0),      // 8: optimizer.v1.ParticipationStatus
	(Category)(0),                 // 9: optimizer.v1.Category
}
var file_optimizer_v1_constraints_proto_depIdxs = []int32{
	0,  // 0: optimizer.v1.Budget.mode:type_name -> optimizer.v1.BudgetMode
	6,  // 1: optimizer.v1.Budget.limit:type_name -> optimizer.v1.Money
	6,  // 2: optimizer.v1.ProgramBalance.balance:type_name -> optimizer.v1.Money
	7,  // 3: optimizer.v1.RouteObligation.starts_at:type_name -> google.protobuf.Timestamp
	8,  // 4: optimizer.v1.RouteObligation.participation:type_name -> optimizer.v1.ParticipationStatus
	7,  // 5: optimizer.v1.LunchWindow.start_at:type_name -> google.protobuf.Timestamp
	7,  // 6: optimizer.v1.LunchWindow.end_at:type_name -> google.protobuf.Timestamp
	9,  // 7: optimizer.v1.RouteConstraints.excluded_categories:type_name -> optimizer.v1.Category
	1,  // 8: optimizer.v1.RouteConstraints.budget:type_name -> optimizer.v1.Budget
	2,  // 9: optimizer.v1.RouteConstraints.program_balance:type_name -> optimizer.v1.ProgramBalance
	3,  // 10: optimizer.v1.RouteConstraints.obligations:type_name -> optimizer.v1.RouteObligation
	4,  // 11: optimizer.v1.RouteConstraints.lunch_window:type_name -> optimizer.v1.LunchWindow
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_optimizer_v1_constraints_proto_init() }
func file_optimizer_v1_constraints_proto_init() {
	if File_optimizer_v1_constraints_proto != nil {
		return
	}
	file_optimizer_v1_values_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_v1_constraints_proto_rawDesc), len(file_optimizer_v1_constraints_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optimizer_v1_constraints_proto_goTypes,
		DependencyIndexes: file_optimizer_v1_constraints_proto_depIdxs,
		EnumInfos:         file_optimizer_v1_constraints_proto_enumTypes,
		MessageInfos:      file_optimizer_v1_constraints_proto_msgTypes,
	}.Build()
	File_optimizer_v1_constraints_proto = out.File
	file_optimizer_v1_constraints_proto_goTypes = nil
	file_optimizer_v1_constraints_proto_depIdxs = nil
}
