// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: optimizer/v1/lunch.proto

package optimizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExternalVenueAvailability int32

const (
	ExternalVenueAvailability_EXTERNAL_VENUE_AVAILABILITY_UNSPECIFIED ExternalVenueAvailability = 0
	ExternalVenueAvailability_EXTERNAL_VENUE_AVAILABILITY_UNKNOWN     ExternalVenueAvailability = 1
)

// Enum value maps for ExternalVenueAvailability.
var (
	ExternalVenueAvailability_name = map[int32]string{
		0: "EXTERNAL_VENUE_AVAILABILITY_UNSPECIFIED",
		1: "EXTERNAL_VENUE_AVAILABILITY_UNKNOWN",
	}
	ExternalVenueAvailability_value = map[string]int32{
		"EXTERNAL_VENUE_AVAILABILITY_UNSPECIFIED": 0,
		"EXTERNAL_VENUE_AVAILABILITY_UNKNOWN":     1,
	}
)

func (x ExternalVenueAvailability) Enum() *ExternalVenueAvailability {
	p := new(ExternalVenueAvailability)
	*p = x
	return p
}

func (x ExternalVenueAvailability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExternalVenueAvailability) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_lunch_proto_enumTypes[0].Descriptor()
}

func (ExternalVenueAvailability) Type() protoreflect.EnumType {
	return &file_optimizer_v1_lunch_proto_enumTypes[0]
}

func (x ExternalVenueAvailability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExternalVenueAvailability.Descriptor instead.
func (ExternalVenueAvailability) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_lunch_proto_rawDescGZIP(), []int{0}
}

type LunchMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AfterVisitId    []byte                 `protobuf:"bytes,1,opt,name=after_visit_id,json=afterVisitId,proto3" json:"after_visit_id,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LunchMetadata) Reset() {
	*x = LunchMetadata{}
	mi := &file_optimizer_v1_lunch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LunchMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunchMetadata) ProtoMessage() {}

func (x *LunchMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_lunch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunchMetadata.ProtoReflect.Descriptor instead.
func (*LunchMetadata) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_lunch_proto_rawDescGZIP(), []int{0}
}

func (x *LunchMetadata) GetAfterVisitId() []byte {
	if x != nil {
		return x.AfterVisitId
	}
	return nil
}

func (x *LunchMetadata) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type ExternalVenueSnapshot struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Provider          string                    `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalId        string                    `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Title             string                    `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Position          *Coordinate               `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Address           string                    `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ObservedAt        *timestamppb.Timestamp    `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Price             *Price                    `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Availability      ExternalVenueAvailability `protobuf:"varint,8,opt,name=availability,proto3,enum=optimizer.v1.ExternalVenueAvailability" json:"availability,omitempty"`
	HoursVerification VerificationStatus        `protobuf:"varint,9,opt,name=hours_verification,json=hoursVerification,proto3,enum=optimizer.v1.VerificationStatus" json:"hours_verification,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExternalVenueSnapshot) Reset() {
	*x = ExternalVenueSnapshot{}
	mi := &file_optimizer_v1_lunch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalVenueSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalVenueSnapshot) ProtoMessage() {}

func (x *ExternalVenueSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_lunch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalVenueSnapshot.ProtoReflect.Descriptor instead.
func (*ExternalVenueSnapshot) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_lunch_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalVenueSnapshot) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ExternalVenueSnapshot) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ExternalVenueSnapshot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ExternalVenueSnapshot) GetPosition() *Coordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ExternalVenueSnapshot) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ExternalVenueSnapshot) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ExternalVenueSnapshot) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *ExternalVenueSnapshot) GetAvailability() ExternalVenueAvailability {
	if x != nil {
		return x.Availability
	}
	return ExternalVenueAvailability_EXTERNAL_VENUE_AVAILABILITY_UNSPECIFIED
}

func (x *ExternalVenueSnapshot) GetHoursVerification() VerificationStatus {
	if x != nil {
		return x.HoursVerification
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

type LunchStop struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VisitId         []byte                 `protobuf:"bytes,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	AfterVisitId    []byte                 `protobuf:"bytes,2,opt,name=after_visit_id,json=afterVisitId,proto3" json:"after_visit_id,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// Types that are valid to be assigned to Venue:
	//
	//	*LunchStop_External
	//	*LunchStop_CatalogVisitId
	Venue         isLunchStop_Venue `protobuf_oneof:"venue"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LunchStop) Reset() {
	*x = LunchStop{}
	mi := &file_optimizer_v1_lunch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LunchStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunchStop) ProtoMessage() {}

func (x *LunchStop) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_lunch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunchStop.ProtoReflect.Descriptor instead.
func (*LunchStop) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_lunch_proto_rawDescGZIP(), []int{2}
}

func (x *LunchStop) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *LunchStop) GetAfterVisitId() []byte {
	if x != nil {
		return x.AfterVisitId
	}
	return nil
}

func (x *LunchStop) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *LunchStop) GetVenue() isLunchStop_Venue {
	if x != nil {
		return x.Venue
	}
	return nil
}

func (x *LunchStop) GetExternal() *ExternalVenueSnapshot {
	if x != nil {
		if x, ok := x.Venue.(*LunchStop_External); ok {
			return x.External
		}
	}
	return nil
}

func (x *LunchStop) GetCatalogVisitId() []byte {
	if x != nil {
		if x, ok := x.Venue.(*LunchStop_CatalogVisitId); ok {
			return x.CatalogVisitId
		}
	}
	return nil
}

type isLunchStop_Venue interface {
	isLunchStop_Venue()
}

type LunchStop_External struct {
	External *ExternalVenueSnapshot `protobuf:"bytes,4,opt,name=external,proto3,oneof"`
}

type LunchStop_CatalogVisitId struct {
	CatalogVisitId []byte `protobuf:"bytes,5,opt,name=catalog_visit_id,json=catalogVisitId,proto3,oneof"`
}

func (*LunchStop_External) isLunchStop_Venue() {}

func (*LunchStop_CatalogVisitId) isLunchStop_Venue() {}

type LunchTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Stops         []*LunchStop           `protobuf:"bytes,2,rep,name=stops,proto3" json:"stops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LunchTrigger) Reset() {
	*x = LunchTrigger{}
	mi := &file_optimizer_v1_lunch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LunchTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LunchTrigger) ProtoMessage() {}

func (x *LunchTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_lunch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LunchTrigger.ProtoReflect.Descriptor instead.
func (*LunchTrigger) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_lunch_proto_rawDescGZIP(), []int{3}
}

func (x *LunchTrigger) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *LunchTrigger) GetStops() []*LunchStop {
	if x != nil {
		return x.Stops
	}
	return nil
}

var File_optimizer_v1_lunch_proto protoreflect.FileDescriptor

const file_optimizer_v1_lunch_proto_rawDesc = "" +
	"\n" +
	"\x18optimizer/v1/lunch.proto\x12\foptimizer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19optimizer/v1/values.proto\"`\n" +
	"\rLunchMetadata\x12$\n" +
	"\x0eafter_visit_id\x18\x01 \x01(\fR\fafterVisitId\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x03R\x0fdurationSeconds\"\xc0\x03\n" +
	"\x15ExternalVenueSnapshot\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x124\n" +
	"\bposition\x18\x04 \x01(\v2\x18.optimizer.v1.CoordinateR\bposition\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12)\n" +
	"\x05price\x18\a \x01(\v2\x13.optimizer.v1.PriceR\x05price\x12K\n" +
	"\favailability\x18\b \x01(\x0e2'.optimizer.v1.ExternalVenueAvailabilityR\favailability\x12O\n" +
	"\x12hours_verification\x18\t \x01(\x0e2 .optimizer.v1.VerificationStatusR\x11hoursVerification\"\xef\x01\n" +
	"\tLunchStop\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\fR\avisitId\x12$\n" +
	"\x0eafter_visit_id\x18\x02 \x01(\fR\fafterVisitId\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x12A\n" +
	"\bexternal\x18\x04 \x01(\v2#.optimizer.v1.ExternalVenueSnapshotH\x00R\bexternal\x12*\n" +
	"\x10catalog_visit_id\x18\x05 \x01(\fH\x00R\x0ecatalogVisitIdB\a\n" +
	"\x05venue\"d\n" +
	"\fLunchTrigger\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12-\n" +
	"\x05stops\x18\x02 \x03(\v2\x17.optimizer.v1.LunchStopR\x05stops*q\n" +
	"\x19ExternalVenueAvailability\x12+\n" +
	"'EXTERNAL_VENUE_AVAILABILITY_UNSPECIFIED\x10\x00\x12'\n" +
	"#EXTERNAL_VENUE_AVAILABILITY_UNKNOWN\x10\x01BBZ@github.com/andres1m/impuls-goroda/proto/optimizer/v1;optimizerv1b\x06proto3"

var (
	file_optimizer_v1_lunch_proto_rawDescOnce sync.Once
	file_optimizer_v1_lunch_proto_rawDescData []byte
)

func file_optimizer_v1_lunch_proto_rawDescGZIP() []byte {
	file_optimizer_v1_lunch_proto_rawDescOnce.Do(func() {
		file_optimizer_v1_lunch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_v1_lunch_proto_rawDesc), len(file_optimizer_v1_lunch_proto_rawDesc)))
	})
	return file_optimizer_v1_lunch_proto_rawDescData
}

var file_optimizer_v1_lunch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_optimizer_v1_lunch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_optimizer_v1_lunch_proto_goTypes = []any{
	(ExternalVenueAvailability)(0), // 0: optimizer.v1.ExternalVenueAvailability
	(*LunchMetadata)(nil),          // 1: optimizer.v1.LunchMetadata
	(*ExternalVenueSnapshot)(nil),  // 2: optimizer.v1.ExternalVenueSnapshot
	(*LunchStop)(nil),              // 3: optimizer.v1.LunchStop
	(*LunchTrigger)(nil),           // 4: optimizer.v1.LunchTrigger
	(*Coordinate)(nil),             // 5: optimizer.v1.Coordinate
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*Price)(nil),                  // 7: optimizer.v1.Price
	(VerificationStatus)(0),        // 8: optimizer.v1.VerificationStatus
}
var file_optimizer_v1_lunch_proto_depIdxs = []int32{
	5, // 0: optimizer.v1.ExternalVenueSnapshot.position:type_name -> optimizer.v1.Coordinate
	6, // 1: optimizer.v1.ExternalVenueSnapshot.observed_at:type_name -> google.protobuf.Timestamp
	7, // 2: optimizer.v1.ExternalVenueSnapshot.price:type_name -> optimizer.v1.Price
	0, // 3: optimizer.v1.ExternalVenueSnapshot.availability:type_name -> optimizer.v1.ExternalVenueAvailability
	8, // 4: optimizer.v1.ExternalVenueSnapshot.hours_verification:type_name -> optimizer.v1.VerificationStatus
	2, // 5: optimizer.v1.LunchStop.external:type_name -> optimizer.v1.ExternalVenueSnapshot
	3, // 6: optimizer.v1.LunchTrigger.stops:type_name -> optimizer.v1.LunchStop
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_optimizer_v1_lunch_proto_init() }
func file_optimizer_v1_lunch_proto_init() {
	if File_optimizer_v1_lunch_proto != nil {
		return
	}
	file_optimizer_v1_values_proto_init()
	file_optimizer_v1_lunch_proto_msgTypes[2].OneofWrappers = []any{
		(*LunchStop_External)(nil),
		(*LunchStop_CatalogVisitId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_v1_lunch_proto_rawDesc), len(file_optimizer_v1_lunch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optimizer_v1_lunch_proto_goTypes,
		DependencyIndexes: file_optimizer_v1_lunch_proto_depIdxs,
		EnumInfos:         file_optimizer_v1_lunch_proto_enumTypes,
		MessageInfos:      file_optimizer_v1_lunch_proto_msgTypes,
	}.Build()
	File_optimizer_v1_lunch_proto = out.File
	file_optimizer_v1_lunch_proto_goTypes = nil
	file_optimizer_v1_lunch_proto_depIdxs = nil
}
