// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: optimizer/v1/optimizer.proto

package optimizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionStatus int32

const (
	ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED ExecutionStatus = 0
	ExecutionStatus_EXECUTION_STATUS_COMPLETED   ExecutionStatus = 1
	ExecutionStatus_EXECUTION_STATUS_SKIPPED     ExecutionStatus = 2
)

// Enum value maps for ExecutionStatus.
var (
	ExecutionStatus_name = map[int32]string{
		0: "EXECUTION_STATUS_UNSPECIFIED",
		1: "EXECUTION_STATUS_COMPLETED",
		2: "EXECUTION_STATUS_SKIPPED",
	}
	ExecutionStatus_value = map[string]int32{
		"EXECUTION_STATUS_UNSPECIFIED": 0,
		"EXECUTION_STATUS_COMPLETED":   1,
		"EXECUTION_STATUS_SKIPPED":     2,
	}
)

func (x ExecutionStatus) Enum() *ExecutionStatus {
	p := new(ExecutionStatus)
	*p = x
	return p
}

func (x ExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[0].Descriptor()
}

func (ExecutionStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[0]
}

func (x ExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionStatus.Descriptor instead.
func (ExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{0}
}

type DelayMode int32

const (
	DelayMode_DELAY_MODE_UNSPECIFIED     DelayMode = 0
	DelayMode_DELAY_MODE_ALREADY_DELAYED DelayMode = 1
	DelayMode_DELAY_MODE_FUTURE_WAIT     DelayMode = 2
)

// Enum value maps for DelayMode.
var (
	DelayMode_name = map[int32]string{
		0: "DELAY_MODE_UNSPECIFIED",
		1: "DELAY_MODE_ALREADY_DELAYED",
		2: "DELAY_MODE_FUTURE_WAIT",
	}
	DelayMode_value = map[string]int32{
		"DELAY_MODE_UNSPECIFIED":     0,
		"DELAY_MODE_ALREADY_DELAYED": 1,
		"DELAY_MODE_FUTURE_WAIT":     2,
	}
)

func (x DelayMode) Enum() *DelayMode {
	p := new(DelayMode)
	*p = x
	return p
}

func (x DelayMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DelayMode) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[1].Descriptor()
}

func (DelayMode) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[1]
}

func (x DelayMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DelayMode.Descriptor instead.
func (DelayMode) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{1}
}

type PositionSource int32

const (
	PositionSource_POSITION_SOURCE_UNSPECIFIED PositionSource = 0
	PositionSource_POSITION_SOURCE_DEVICE      PositionSource = 1
	PositionSource_POSITION_SOURCE_MANUAL      PositionSource = 2
)

// Enum value maps for PositionSource.
var (
	PositionSource_name = map[int32]string{
		0: "POSITION_SOURCE_UNSPECIFIED",
		1: "POSITION_SOURCE_DEVICE",
		2: "POSITION_SOURCE_MANUAL",
	}
	PositionSource_value = map[string]int32{
		"POSITION_SOURCE_UNSPECIFIED": 0,
		"POSITION_SOURCE_DEVICE":      1,
		"POSITION_SOURCE_MANUAL":      2,
	}
)

func (x PositionSource) Enum() *PositionSource {
	p := new(PositionSource)
	*p = x
	return p
}

func (x PositionSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PositionSource) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[2].Descriptor()
}

func (PositionSource) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[2]
}

func (x PositionSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PositionSource.Descriptor instead.
func (PositionSource) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{2}
}

type RemovalMode int32

const (
	RemovalMode_REMOVAL_MODE_UNSPECIFIED RemovalMode = 0
	RemovalMode_REMOVAL_MODE_REBUILD     RemovalMode = 1
	RemovalMode_REMOVAL_MODE_FREE_TIME   RemovalMode = 2
)

// Enum value maps for RemovalMode.
var (
	RemovalMode_name = map[int32]string{
		0: "REMOVAL_MODE_UNSPECIFIED",
		1: "REMOVAL_MODE_REBUILD",
		2: "REMOVAL_MODE_FREE_TIME",
	}
	RemovalMode_value = map[string]int32{
		"REMOVAL_MODE_UNSPECIFIED": 0,
		"REMOVAL_MODE_REBUILD":     1,
		"REMOVAL_MODE_FREE_TIME":   2,
	}
)

func (x RemovalMode) Enum() *RemovalMode {
	p := new(RemovalMode)
	*p = x
	return p
}

func (x RemovalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemovalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[3].Descriptor()
}

func (RemovalMode) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[3]
}

func (x RemovalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemovalMode.Descriptor instead.
func (RemovalMode) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{3}
}

type PinKind int32

const (
	PinKind_PIN_KIND_UNSPECIFIED PinKind = 0
	PinKind_PIN_KIND_PREFERRED   PinKind = 1
	PinKind_PIN_KIND_OBLIGATION  PinKind = 2
	PinKind_PIN_KIND_NONE        PinKind = 3
)

// Enum value maps for PinKind.
var (
	PinKind_name = map[int32]string{
		0: "PIN_KIND_UNSPECIFIED",
		1: "PIN_KIND_PREFERRED",
		2: "PIN_KIND_OBLIGATION",
		3: "PIN_KIND_NONE",
	}
	PinKind_value = map[string]int32{
		"PIN_KIND_UNSPECIFIED": 0,
		"PIN_KIND_PREFERRED":   1,
		"PIN_KIND_OBLIGATION":  2,
		"PIN_KIND_NONE":        3,
	}
)

func (x PinKind) Enum() *PinKind {
	p := new(PinKind)
	*p = x
	return p
}

func (x PinKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PinKind) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[4].Descriptor()
}

func (PinKind) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[4]
}

func (x PinKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PinKind.Descriptor instead.
func (PinKind) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{4}
}

type RecomputeStatus int32

const (
	RecomputeStatus_RECOMPUTE_STATUS_UNSPECIFIED RecomputeStatus = 0
	RecomputeStatus_RECOMPUTE_STATUS_PROPOSED    RecomputeStatus = 1
	RecomputeStatus_RECOMPUTE_STATUS_UNCHANGED   RecomputeStatus = 2
	RecomputeStatus_RECOMPUTE_STATUS_CONFLICT    RecomputeStatus = 3
)

// Enum value maps for RecomputeStatus.
var (
	RecomputeStatus_name = map[int32]string{
		0: "RECOMPUTE_STATUS_UNSPECIFIED",
		1: "RECOMPUTE_STATUS_PROPOSED",
		2: "RECOMPUTE_STATUS_UNCHANGED",
		3: "RECOMPUTE_STATUS_CONFLICT",
	}
	RecomputeStatus_value = map[string]int32{
		"RECOMPUTE_STATUS_UNSPECIFIED": 0,
		"RECOMPUTE_STATUS_PROPOSED":    1,
		"RECOMPUTE_STATUS_UNCHANGED":   2,
		"RECOMPUTE_STATUS_CONFLICT":    3,
	}
)

func (x RecomputeStatus) Enum() *RecomputeStatus {
	p := new(RecomputeStatus)
	*p = x
	return p
}

func (x RecomputeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecomputeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[5].Descriptor()
}

func (RecomputeStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[5]
}

func (x RecomputeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecomputeStatus.Descriptor instead.
func (RecomputeStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{5}
}

type RouteChangeKind int32

const (
	RouteChangeKind_ROUTE_CHANGE_KIND_UNSPECIFIED          RouteChangeKind = 0
	RouteChangeKind_ROUTE_CHANGE_KIND_KEPT                 RouteChangeKind = 1
	RouteChangeKind_ROUTE_CHANGE_KIND_REMOVED              RouteChangeKind = 2
	RouteChangeKind_ROUTE_CHANGE_KIND_REPLACED             RouteChangeKind = 3
	RouteChangeKind_ROUTE_CHANGE_KIND_TIME_SHIFTED         RouteChangeKind = 4
	RouteChangeKind_ROUTE_CHANGE_KIND_COST_CHANGED         RouteChangeKind = 5
	RouteChangeKind_ROUTE_CHANGE_KIND_PARTICIPATION_ACTION RouteChangeKind = 6
	RouteChangeKind_ROUTE_CHANGE_KIND_VERIFICATION_CHANGED RouteChangeKind = 7
)

// Enum value maps for RouteChangeKind.
var (
	RouteChangeKind_name = map[int32]string{
		0: "ROUTE_CHANGE_KIND_UNSPECIFIED",
		1: "ROUTE_CHANGE_KIND_KEPT",
		2: "ROUTE_CHANGE_KIND_REMOVED",
		3: "ROUTE_CHANGE_KIND_REPLACED",
		4: "ROUTE_CHANGE_KIND_TIME_SHIFTED",
		5: "ROUTE_CHANGE_KIND_COST_CHANGED",
		6: "ROUTE_CHANGE_KIND_PARTICIPATION_ACTION",
		7: "ROUTE_CHANGE_KIND_VERIFICATION_CHANGED",
	}
	RouteChangeKind_value = map[string]int32{
		"ROUTE_CHANGE_KIND_UNSPECIFIED":          0,
		"ROUTE_CHANGE_KIND_KEPT":                 1,
		"ROUTE_CHANGE_KIND_REMOVED":              2,
		"ROUTE_CHANGE_KIND_REPLACED":             3,
		"ROUTE_CHANGE_KIND_TIME_SHIFTED":         4,
		"ROUTE_CHANGE_KIND_COST_CHANGED":         5,
		"ROUTE_CHANGE_KIND_PARTICIPATION_ACTION": 6,
		"ROUTE_CHANGE_KIND_VERIFICATION_CHANGED": 7,
	}
)

func (x RouteChangeKind) Enum() *RouteChangeKind {
	p := new(RouteChangeKind)
	*p = x
	return p
}

func (x RouteChangeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteChangeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_optimizer_proto_enumTypes[6].Descriptor()
}

func (RouteChangeKind) Type() protoreflect.EnumType {
	return &file_optimizer_v1_optimizer_proto_enumTypes[6]
}

func (x RouteChangeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteChangeKind.Descriptor instead.
func (RouteChangeKind) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{6}
}

type OptimizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	City  string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	// IANA time zone of the city.
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Origin        *Coordinate            `protobuf:"bytes,5,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination   *Coordinate            `protobuf:"bytes,6,opt,name=destination,proto3" json:"destination,omitempty"`
	Constraints   *RouteConstraints      `protobuf:"bytes,7,opt,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizeRequest) Reset() {
	*x = OptimizeRequest{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeRequest) ProtoMessage() {}

func (x *OptimizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeRequest.ProtoReflect.Descriptor instead.
func (*OptimizeRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizeRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OptimizeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *OptimizeRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *OptimizeRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *OptimizeRequest) GetOrigin() *Coordinate {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *OptimizeRequest) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *OptimizeRequest) GetConstraints() *RouteConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type OptimizeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status ResultStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=optimizer.v1.ResultStatus" json:"status,omitempty"`
	// Up to one route per archetype; identical plans are not repeated under different archetypes.
	Routes            []*RoutePlan   `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Warnings          []*Warning     `protobuf:"bytes,3,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Conflicts         []*Conflict    `protobuf:"bytes,4,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Data              *DataFreshness `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	ComputationTimeMs uint32         `protobuf:"varint,6,opt,name=computation_time_ms,json=computationTimeMs,proto3" json:"computation_time_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *OptimizeResponse) Reset() {
	*x = OptimizeResponse{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizeResponse) ProtoMessage() {}

func (x *OptimizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizeResponse.ProtoReflect.Descriptor instead.
func (*OptimizeResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{1}
}

func (x *OptimizeResponse) GetStatus() ResultStatus {
	if x != nil {
		return x.Status
	}
	return ResultStatus_RESULT_STATUS_UNSPECIFIED
}

func (x *OptimizeResponse) GetRoutes() []*RoutePlan {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *OptimizeResponse) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *OptimizeResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *OptimizeResponse) GetData() *DataFreshness {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OptimizeResponse) GetComputationTimeMs() uint32 {
	if x != nil {
		return x.ComputationTimeMs
	}
	return 0
}

// Actual history of a visit. Visits without a record are still planned.
type VisitExecution struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	VisitId         []byte                 `protobuf:"bytes,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	Status          ExecutionStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=optimizer.v1.ExecutionStatus" json:"status,omitempty"`
	ActualStartedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=actual_started_at,json=actualStartedAt,proto3" json:"actual_started_at,omitempty"`
	ActualEndedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=actual_ended_at,json=actualEndedAt,proto3" json:"actual_ended_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VisitExecution) Reset() {
	*x = VisitExecution{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisitExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisitExecution) ProtoMessage() {}

func (x *VisitExecution) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisitExecution.ProtoReflect.Descriptor instead.
func (*VisitExecution) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{2}
}

func (x *VisitExecution) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *VisitExecution) GetStatus() ExecutionStatus {
	if x != nil {
		return x.Status
	}
	return ExecutionStatus_EXECUTION_STATUS_UNSPECIFIED
}

func (x *VisitExecution) GetActualStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualStartedAt
	}
	return nil
}

func (x *VisitExecution) GetActualEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActualEndedAt
	}
	return nil
}

type DelayTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  DelayMode              `protobuf:"varint,1,opt,name=mode,proto3,enum=optimizer.v1.DelayMode" json:"mode,omitempty"`
	// Resolved by the caller: the reported time for an existing delay, or now plus the wait.
	EffectiveStartAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=effective_start_at,json=effectiveStartAt,proto3" json:"effective_start_at,omitempty"`
	Position         *Coordinate            `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	PositionSource   PositionSource         `protobuf:"varint,4,opt,name=position_source,json=positionSource,proto3,enum=optimizer.v1.PositionSource" json:"position_source,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DelayTrigger) Reset() {
	*x = DelayTrigger{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelayTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelayTrigger) ProtoMessage() {}

func (x *DelayTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelayTrigger.ProtoReflect.Descriptor instead.
func (*DelayTrigger) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{3}
}

func (x *DelayTrigger) GetMode() DelayMode {
	if x != nil {
		return x.Mode
	}
	return DelayMode_DELAY_MODE_UNSPECIFIED
}

func (x *DelayTrigger) GetEffectiveStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveStartAt
	}
	return nil
}

func (x *DelayTrigger) GetPosition() *Coordinate {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *DelayTrigger) GetPositionSource() PositionSource {
	if x != nil {
		return x.PositionSource
	}
	return PositionSource_POSITION_SOURCE_UNSPECIFIED
}

type CancellationTrigger struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VisitIds [][]byte               `protobuf:"bytes,1,rep,name=visit_ids,json=visitIds,proto3" json:"visit_ids,omitempty"`
	// The result must be computed on this catalog revision or a newer one.
	MinCatalogRevision int64 `protobuf:"varint,2,opt,name=min_catalog_revision,json=minCatalogRevision,proto3" json:"min_catalog_revision,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CancellationTrigger) Reset() {
	*x = CancellationTrigger{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancellationTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancellationTrigger) ProtoMessage() {}

func (x *CancellationTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancellationTrigger.ProtoReflect.Descriptor instead.
func (*CancellationTrigger) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{4}
}

func (x *CancellationTrigger) GetVisitIds() [][]byte {
	if x != nil {
		return x.VisitIds
	}
	return nil
}

func (x *CancellationTrigger) GetMinCatalogRevision() int64 {
	if x != nil {
		return x.MinCatalogRevision
	}
	return 0
}

type RemovalTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitId       []byte                 `protobuf:"bytes,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	Mode          RemovalMode            `protobuf:"varint,2,opt,name=mode,proto3,enum=optimizer.v1.RemovalMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovalTrigger) Reset() {
	*x = RemovalTrigger{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovalTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovalTrigger) ProtoMessage() {}

func (x *RemovalTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovalTrigger.ProtoReflect.Descriptor instead.
func (*RemovalTrigger) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{5}
}

func (x *RemovalTrigger) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *RemovalTrigger) GetMode() RemovalMode {
	if x != nil {
		return x.Mode
	}
	return RemovalMode_REMOVAL_MODE_UNSPECIFIED
}

type PinTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitId       []byte                 `protobuf:"bytes,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	Kind          PinKind                `protobuf:"varint,2,opt,name=kind,proto3,enum=optimizer.v1.PinKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinTrigger) Reset() {
	*x = PinTrigger{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinTrigger) ProtoMessage() {}

func (x *PinTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinTrigger.ProtoReflect.Descriptor instead.
func (*PinTrigger) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{6}
}

func (x *PinTrigger) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *PinTrigger) GetKind() PinKind {
	if x != nil {
		return x.Kind
	}
	return PinKind_PIN_KIND_UNSPECIFIED
}

type RecomputeRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	City        string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Timezone    string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	BasePlan    *RoutePlan             `protobuf:"bytes,3,opt,name=base_plan,json=basePlan,proto3" json:"base_plan,omitempty"`
	Constraints *RouteConstraints      `protobuf:"bytes,4,opt,name=constraints,proto3" json:"constraints,omitempty"`
	History     []*VisitExecution      `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	// Types that are valid to be assigned to Trigger:
	//
	//	*RecomputeRequest_Delay
	//	*RecomputeRequest_Cancellation
	//	*RecomputeRequest_Removal
	//	*RecomputeRequest_Pin
	Trigger       isRecomputeRequest_Trigger `protobuf_oneof:"trigger"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecomputeRequest) Reset() {
	*x = RecomputeRequest{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomputeRequest) ProtoMessage() {}

func (x *RecomputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomputeRequest.ProtoReflect.Descriptor instead.
func (*RecomputeRequest) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{7}
}

func (x *RecomputeRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RecomputeRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *RecomputeRequest) GetBasePlan() *RoutePlan {
	if x != nil {
		return x.BasePlan
	}
	return nil
}

func (x *RecomputeRequest) GetConstraints() *RouteConstraints {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *RecomputeRequest) GetHistory() []*VisitExecution {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *RecomputeRequest) GetTrigger() isRecomputeRequest_Trigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *RecomputeRequest) GetDelay() *DelayTrigger {
	if x != nil {
		if x, ok := x.Trigger.(*RecomputeRequest_Delay); ok {
			return x.Delay
		}
	}
	return nil
}

func (x *RecomputeRequest) GetCancellation() *CancellationTrigger {
	if x != nil {
		if x, ok := x.Trigger.(*RecomputeRequest_Cancellation); ok {
			return x.Cancellation
		}
	}
	return nil
}

func (x *RecomputeRequest) GetRemoval() *RemovalTrigger {
	if x != nil {
		if x, ok := x.Trigger.(*RecomputeRequest_Removal); ok {
			return x.Removal
		}
	}
	return nil
}

func (x *RecomputeRequest) GetPin() *PinTrigger {
	if x != nil {
		if x, ok := x.Trigger.(*RecomputeRequest_Pin); ok {
			return x.Pin
		}
	}
	return nil
}

type isRecomputeRequest_Trigger interface {
	isRecomputeRequest_Trigger()
}

type RecomputeRequest_Delay struct {
	Delay *DelayTrigger `protobuf:"bytes,10,opt,name=delay,proto3,oneof"`
}

type RecomputeRequest_Cancellation struct {
	Cancellation *CancellationTrigger `protobuf:"bytes,11,opt,name=cancellation,proto3,oneof"`
}

type RecomputeRequest_Removal struct {
	Removal *RemovalTrigger `protobuf:"bytes,12,opt,name=removal,proto3,oneof"`
}

type RecomputeRequest_Pin struct {
	Pin *PinTrigger `protobuf:"bytes,13,opt,name=pin,proto3,oneof"`
}

func (*RecomputeRequest_Delay) isRecomputeRequest_Trigger() {}

func (*RecomputeRequest_Cancellation) isRecomputeRequest_Trigger() {}

func (*RecomputeRequest_Removal) isRecomputeRequest_Trigger() {}

func (*RecomputeRequest_Pin) isRecomputeRequest_Trigger() {}

type CostChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *Money                 `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	After         *Money                 `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CostChange) Reset() {
	*x = CostChange{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostChange) ProtoMessage() {}

func (x *CostChange) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostChange.ProtoReflect.Descriptor instead.
func (*CostChange) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{8}
}

func (x *CostChange) GetBefore() *Money {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *CostChange) GetAfter() *Money {
	if x != nil {
		return x.After
	}
	return nil
}

type VerificationChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        VerificationStatus     `protobuf:"varint,1,opt,name=before,proto3,enum=optimizer.v1.VerificationStatus" json:"before,omitempty"`
	After         VerificationStatus     `protobuf:"varint,2,opt,name=after,proto3,enum=optimizer.v1.VerificationStatus" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationChange) Reset() {
	*x = VerificationChange{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationChange) ProtoMessage() {}

func (x *VerificationChange) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationChange.ProtoReflect.Descriptor instead.
func (*VerificationChange) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{9}
}

func (x *VerificationChange) GetBefore() VerificationStatus {
	if x != nil {
		return x.Before
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *VerificationChange) GetAfter() VerificationStatus {
	if x != nil {
		return x.After
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

type RouteChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          RouteChangeKind        `protobuf:"varint,1,opt,name=kind,proto3,enum=optimizer.v1.RouteChangeKind" json:"kind,omitempty"`
	Scope         TargetScope            `protobuf:"varint,2,opt,name=scope,proto3,enum=optimizer.v1.TargetScope" json:"scope,omitempty"`
	BeforeVisitId []byte                 `protobuf:"bytes,3,opt,name=before_visit_id,json=beforeVisitId,proto3" json:"before_visit_id,omitempty"`
	AfterVisitId  []byte                 `protobuf:"bytes,4,opt,name=after_visit_id,json=afterVisitId,proto3" json:"after_visit_id,omitempty"`
	LegPosition   *uint32                `protobuf:"varint,5,opt,name=leg_position,json=legPosition,proto3,oneof" json:"leg_position,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*RouteChange_TimeShiftSeconds
	//	*RouteChange_Cost
	//	*RouteChange_ParticipationAction
	//	*RouteChange_Verification
	Details       isRouteChange_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteChange) Reset() {
	*x = RouteChange{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteChange) ProtoMessage() {}

func (x *RouteChange) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteChange.ProtoReflect.Descriptor instead.
func (*RouteChange) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{10}
}

func (x *RouteChange) GetKind() RouteChangeKind {
	if x != nil {
		return x.Kind
	}
	return RouteChangeKind_ROUTE_CHANGE_KIND_UNSPECIFIED
}

func (x *RouteChange) GetScope() TargetScope {
	if x != nil {
		return x.Scope
	}
	return TargetScope_TARGET_SCOPE_UNSPECIFIED
}

func (x *RouteChange) GetBeforeVisitId() []byte {
	if x != nil {
		return x.BeforeVisitId
	}
	return nil
}

func (x *RouteChange) GetAfterVisitId() []byte {
	if x != nil {
		return x.AfterVisitId
	}
	return nil
}

func (x *RouteChange) GetLegPosition() uint32 {
	if x != nil && x.LegPosition != nil {
		return *x.LegPosition
	}
	return 0
}

func (x *RouteChange) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RouteChange) GetDetails() isRouteChange_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *RouteChange) GetTimeShiftSeconds() int64 {
	if x != nil {
		if x, ok := x.Details.(*RouteChange_TimeShiftSeconds); ok {
			return x.TimeShiftSeconds
		}
	}
	return 0
}

func (x *RouteChange) GetCost() *CostChange {
	if x != nil {
		if x, ok := x.Details.(*RouteChange_Cost); ok {
			return x.Cost
		}
	}
	return nil
}

func (x *RouteChange) GetParticipationAction() string {
	if x != nil {
		if x, ok := x.Details.(*RouteChange_ParticipationAction); ok {
			return x.ParticipationAction
		}
	}
	return ""
}

func (x *RouteChange) GetVerification() *VerificationChange {
	if x != nil {
		if x, ok := x.Details.(*RouteChange_Verification); ok {
			return x.Verification
		}
	}
	return nil
}

type isRouteChange_Details interface {
	isRouteChange_Details()
}

type RouteChange_TimeShiftSeconds struct {
	TimeShiftSeconds int64 `protobuf:"varint,10,opt,name=time_shift_seconds,json=timeShiftSeconds,proto3,oneof"`
}

type RouteChange_Cost struct {
	Cost *CostChange `protobuf:"bytes,11,opt,name=cost,proto3,oneof"`
}

type RouteChange_ParticipationAction struct {
	ParticipationAction string `protobuf:"bytes,12,opt,name=participation_action,json=participationAction,proto3,oneof"`
}

type RouteChange_Verification struct {
	Verification *VerificationChange `protobuf:"bytes,13,opt,name=verification,proto3,oneof"`
}

func (*RouteChange_TimeShiftSeconds) isRouteChange_Details() {}

func (*RouteChange_Cost) isRouteChange_Details() {}

func (*RouteChange_ParticipationAction) isRouteChange_Details() {}

func (*RouteChange_Verification) isRouteChange_Details() {}

type RecomputeResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status RecomputeStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=optimizer.v1.RecomputeStatus" json:"status,omitempty"`
	// Absent when the status is UNCHANGED or when no feasible candidate exists.
	Candidate         *RoutePlan     `protobuf:"bytes,2,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Changes           []*RouteChange `protobuf:"bytes,3,rep,name=changes,proto3" json:"changes,omitempty"`
	Conflicts         []*Conflict    `protobuf:"bytes,4,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Data              *DataFreshness `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	ComputationTimeMs uint32         `protobuf:"varint,6,opt,name=computation_time_ms,json=computationTimeMs,proto3" json:"computation_time_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecomputeResponse) Reset() {
	*x = RecomputeResponse{}
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecomputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecomputeResponse) ProtoMessage() {}

func (x *RecomputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_optimizer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecomputeResponse.ProtoReflect.Descriptor instead.
func (*RecomputeResponse) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_optimizer_proto_rawDescGZIP(), []int{11}
}

func (x *RecomputeResponse) GetStatus() RecomputeStatus {
	if x != nil {
		return x.Status
	}
	return RecomputeStatus_RECOMPUTE_STATUS_UNSPECIFIED
}

func (x *RecomputeResponse) GetCandidate() *RoutePlan {
	if x != nil {
		return x.Candidate
	}
	return nil
}

func (x *RecomputeResponse) GetChanges() []*RouteChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *RecomputeResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *RecomputeResponse) GetData() *DataFreshness {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RecomputeResponse) GetComputationTimeMs() uint32 {
	if x != nil {
		return x.ComputationTimeMs
	}
	return 0
}

var File_optimizer_v1_optimizer_proto protoreflect.FileDescriptor

const file_optimizer_v1_optimizer_proto_rawDesc = "" +
	"\n" +
	"\x1coptimizer/v1/optimizer.proto\x12\foptimizer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1eoptimizer/v1/constraints.proto\x1a\x17optimizer/v1/plan.proto\x1a\x19optimizer/v1/values.proto\"\xdb\x02\n" +
	"\x0fOptimizeRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x125\n" +
	"\bstart_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x120\n" +
	"\x06origin\x18\x05 \x01(\v2\x18.optimizer.v1.CoordinateR\x06origin\x12:\n" +
	"\vdestination\x18\x06 \x01(\v2\x18.optimizer.v1.CoordinateR\vdestination\x12@\n" +
	"\vconstraints\x18\a \x01(\v2\x1e.optimizer.v1.RouteConstraintsR\vconstraints\"\xc1\x02\n" +
	"\x10OptimizeResponse\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.optimizer.v1.ResultStatusR\x06status\x12/\n" +
	"\x06routes\x18\x02 \x03(\v2\x17.optimizer.v1.RoutePlanR\x06routes\x121\n" +
	"\bwarnings\x18\x03 \x03(\v2\x15.optimizer.v1.WarningR\bwarnings\x124\n" +
	"\tconflicts\x18\x04 \x03(\v2\x16.optimizer.v1.ConflictR\tconflicts\x12/\n" +
	"\x04data\x18\x05 \x01(\v2\x1b.optimizer.v1.DataFreshnessR\x04data\x12.\n" +
	"\x13computation_time_ms\x18\x06 \x01(\rR\x11computationTimeMs\"\xee\x01\n" +
	"\x0eVisitExecution\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\fR\avisitId\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.optimizer.v1.ExecutionStatusR\x06status\x12F\n" +
	"\x11actual_started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0factualStartedAt\x12B\n" +
	"\x0factual_ended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ractualEndedAt\"\x82\x02\n" +
	"\fDelayTrigger\x12+\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x17.optimizer.v1.DelayModeR\x04mode\x12H\n" +
	"\x12effective_start_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x10effectiveStartAt\x124\n" +
	"\bposition\x18\x03 \x01(\v2\x18.optimizer.v1.CoordinateR\bposition\x12E\n" +
	"\x0fposition_source\x18\x04 \x01(\x0e2\x1c.optimizer.v1.PositionSourceR\x0epositionSource\"d\n" +
	"\x13CancellationTrigger\x12\x1b\n" +
	"\tvisit_ids\x18\x01 \x03(\fR\bvisitIds\x120\n" +
	"\x14min_catalog_revision\x18\x02 \x01(\x03R\x12minCatalogRevision\"Z\n" +
	"\x0eRemovalTrigger\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\fR\avisitId\x12-\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x19.optimizer.v1.RemovalModeR\x04mode\"R\n" +
	"\n" +
	"PinTrigger\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\fR\avisitId\x12)\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x15.optimizer.v1.PinKindR\x04kind\"\xe2\x03\n" +
	"\x10RecomputeRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x124\n" +
	"\tbase_plan\x18\x03 \x01(\v2\x17.optimizer.v1.RoutePlanR\bbasePlan\x12@\n" +
	"\vconstraints\x18\x04 \x01(\v2\x1e.optimizer.v1.RouteConstraintsR\vconstraints\x126\n" +
	"\ahistory\x18\x05 \x03(\v2\x1c.optimizer.v1.VisitExecutionR\ahistory\x122\n" +
	"\x05delay\x18\n" +
	" \x01(\v2\x1a.optimizer.v1.DelayTriggerH\x00R\x05delay\x12G\n" +
	"\fcancellation\x18\v \x01(\v2!.optimizer.v1.CancellationTriggerH\x00R\fcancellation\x128\n" +
	"\aremoval\x18\f \x01(\v2\x1c.optimizer.v1.RemovalTriggerH\x00R\aremoval\x12,\n" +
	"\x03pin\x18\r \x01(\v2\x18.optimizer.v1.PinTriggerH\x00R\x03pinB\t\n" +
	"\atrigger\"d\n" +
	"\n" +
	"CostChange\x12+\n" +
	"\x06before\x18\x01 \x01(\v2\x13.optimizer.v1.MoneyR\x06before\x12)\n" +
	"\x05after\x18\x02 \x01(\v2\x13.optimizer.v1.MoneyR\x05after\"\x86\x01\n" +
	"\x12VerificationChange\x128\n" +
	"\x06before\x18\x01 \x01(\x0e2 .optimizer.v1.VerificationStatusR\x06before\x126\n" +
	"\x05after\x18\x02 \x01(\x0e2 .optimizer.v1.VerificationStatusR\x05after\"\xfa\x03\n" +
	"\vRouteChange\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.optimizer.v1.RouteChangeKindR\x04kind\x12/\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x19.optimizer.v1.TargetScopeR\x05scope\x12&\n" +
	"\x0fbefore_visit_id\x18\x03 \x01(\fR\rbeforeVisitId\x12$\n" +
	"\x0eafter_visit_id\x18\x04 \x01(\fR\fafterVisitId\x12&\n" +
	"\fleg_position\x18\x05 \x01(\rH\x01R\vlegPosition\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12.\n" +
	"\x12time_shift_seconds\x18\n" +
	" \x01(\x03H\x00R\x10timeShiftSeconds\x12.\n" +
	"\x04cost\x18\v \x01(\v2\x18.optimizer.v1.CostChangeH\x00R\x04cost\x123\n" +
	"\x14participation_action\x18\f \x01(\tH\x00R\x13participationAction\x12F\n" +
	"\fverification\x18\r \x01(\v2 .optimizer.v1.VerificationChangeH\x00R\fverificationB\t\n" +
	"\adetailsB\x0f\n" +
	"\r_leg_position\"\xcd\x02\n" +
	"\x11RecomputeResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.optimizer.v1.RecomputeStatusR\x06status\x125\n" +
	"\tcandidate\x18\x02 \x01(\v2\x17.optimizer.v1.RoutePlanR\tcandidate\x123\n" +
	"\achanges\x18\x03 \x03(\v2\x19.optimizer.v1.RouteChangeR\achanges\x124\n" +
	"\tconflicts\x18\x04 \x03(\v2\x16.optimizer.v1.ConflictR\tconflicts\x12/\n" +
	"\x04data\x18\x05 \x01(\v2\x1b.optimizer.v1.DataFreshnessR\x04data\x12.\n" +
	"\x13computation_time_ms\x18\x06 \x01(\rR\x11computationTimeMs*q\n" +
	"\x0fExecutionStatus\x12 \n" +
	"\x1cEXECUTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aEXECUTION_STATUS_COMPLETED\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_STATUS_SKIPPED\x10\x02*c\n" +
	"\tDelayMode\x12\x1a\n" +
	"\x16DELAY_MODE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aDELAY_MODE_ALREADY_DELAYED\x10\x01\x12\x1a\n" +
	"\x16DELAY_MODE_FUTURE_WAIT\x10\x02*i\n" +
	"\x0ePositionSource\x12\x1f\n" +
	"\x1bPOSITION_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16POSITION_SOURCE_DEVICE\x10\x01\x12\x1a\n" +
	"\x16POSITION_SOURCE_MANUAL\x10\x02*a\n" +
	"\vRemovalMode\x12\x1c\n" +
	"\x18REMOVAL_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14REMOVAL_MODE_REBUILD\x10\x01\x12\x1a\n" +
	"\x16REMOVAL_MODE_FREE_TIME\x10\x02*g\n" +
	"\aPinKind\x12\x18\n" +
	"\x14PIN_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PIN_KIND_PREFERRED\x10\x01\x12\x17\n" +
	"\x13PIN_KIND_OBLIGATION\x10\x02\x12\x11\n" +
	"\rPIN_KIND_NONE\x10\x03*\x91\x01\n" +
	"\x0fRecomputeStatus\x12 \n" +
	"\x1cRECOMPUTE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19RECOMPUTE_STATUS_PROPOSED\x10\x01\x12\x1e\n" +
	"\x1aRECOMPUTE_STATUS_UNCHANGED\x10\x02\x12\x1d\n" +
	"\x19RECOMPUTE_STATUS_CONFLICT\x10\x03*\xaf\x02\n" +
	"\x0fRouteChangeKind\x12!\n" +
	"\x1dROUTE_CHANGE_KIND_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ROUTE_CHANGE_KIND_KEPT\x10\x01\x12\x1d\n" +
	"\x19ROUTE_CHANGE_KIND_REMOVED\x10\x02\x12\x1e\n" +
	"\x1aROUTE_CHANGE_KIND_REPLACED\x10\x03\x12\"\n" +
	"\x1eROUTE_CHANGE_KIND_TIME_SHIFTED\x10\x04\x12\"\n" +
	"\x1eROUTE_CHANGE_KIND_COST_CHANGED\x10\x05\x12*\n" +
	"&ROUTE_CHANGE_KIND_PARTICIPATION_ACTION\x10\x06\x12*\n" +
	"&ROUTE_CHANGE_KIND_VERIFICATION_CHANGED\x10\a2\xab\x01\n" +
	"\x10OptimizerService\x12I\n" +
	"\bOptimize\x12\x1d.optimizer.v1.OptimizeRequest\x1a\x1e.optimizer.v1.OptimizeResponse\x12L\n" +
	"\tRecompute\x12\x1e.optimizer.v1.RecomputeRequest\x1a\x1f.optimizer.v1.RecomputeResponseBBZ@github.com/andres1m/impuls-goroda/proto/optimizer/v1;optimizerv1b\x06proto3"

var (
	file_optimizer_v1_optimizer_proto_rawDescOnce sync.Once
	file_optimizer_v1_optimizer_proto_rawDescData []byte
)

func file_optimizer_v1_optimizer_proto_rawDescGZIP() []byte {
	file_optimizer_v1_optimizer_proto_rawDescOnce.Do(func() {
		file_optimizer_v1_optimizer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_v1_optimizer_proto_rawDesc), len(file_optimizer_v1_optimizer_proto_rawDesc)))
	})
	return file_optimizer_v1_optimizer_proto_rawDescData
}

var file_optimizer_v1_optimizer_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_optimizer_v1_optimizer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_optimizer_v1_optimizer_proto_goTypes = []any{
	(ExecutionStatus)(0),          // 0: optimizer.v1.ExecutionStatus
	(DelayMode)(0),                // 1: optimizer.v1.DelayMode
	(PositionSource)(0),           // 2: optimizer.v1.PositionSource
	(RemovalMode)(0),              // 3: optimizer.v1.RemovalMode
	(PinKind)(0),                  // 4: optimizer.v1.PinKind
	(RecomputeStatus)(0),          // 5: optimizer.v1.RecomputeStatus
	(RouteChangeKind)(0),          // 6: optimizer.v1.RouteChangeKind
	(*OptimizeRequest)(nil),       // 7: optimizer.v1.OptimizeRequest
	(*OptimizeResponse)(nil),      // 8: optimizer.v1.OptimizeResponse
	(*VisitExecution)(nil),        // 9: optimizer.v1.VisitExecution
	(*DelayTrigger)(nil),          // 10: optimizer.v1.DelayTrigger
	(*CancellationTrigger)(nil),   // 11: optimizer.v1.CancellationTrigger
	(*RemovalTrigger)(nil),        // 12: optimizer.v1.RemovalTrigger
	(*PinTrigger)(nil),            // 13: optimizer.v1.PinTrigger
	(*RecomputeRequest)(nil),      // 14: optimizer.v1.RecomputeRequest
	(*CostChange)(nil),            // 15: optimizer.v1.CostChange
	(*VerificationChange)(nil),    // 16: optimizer.v1.VerificationChange
	(*RouteChange)(nil),           // 17: optimizer.v1.RouteChange
	(*RecomputeResponse)(nil),     // 18: optimizer.v1.RecomputeResponse
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
	(*Coordinate)(nil),            // 20: optimizer.v1.Coordinate
	(*RouteConstraints)(nil),      // 21: optimizer.v1.RouteConstraints
	(ResultStatus)(0),             // 22: optimizer.v1.ResultStatus
	(*RoutePlan)(nil),             // 23: optimizer.v1.RoutePlan
	(*Warning)(nil),               // 24: optimizer.v1.Warning
	(*Conflict)(nil),              // 25: optimizer.v1.Conflict
	(*DataFreshness)(nil),         // 26: optimizer.v1.DataFreshness
	(*Money)(nil),                 // 27: optimizer.v1.Money
	(VerificationStatus)(0),       // 28: optimizer.v1.VerificationStatus
	(TargetScope)(0),              // 29: optimizer.v1.TargetScope
}
var file_optimizer_v1_optimizer_proto_depIdxs = []int32{
	19, // 0: optimizer.v1.OptimizeRequest.start_at:type_name -> google.protobuf.Timestamp
	19, // 1: optimizer.v1.OptimizeRequest.end_at:type_name -> google.protobuf.Timestamp
	20, // 2: optimizer.v1.OptimizeRequest.origin:type_name -> optimizer.v1.Coordinate
	20, // 3: optimizer.v1.OptimizeRequest.destination:type_name -> optimizer.v1.Coordinate
	21, // 4: optimizer.v1.OptimizeRequest.constraints:type_name -> optimizer.v1.RouteConstraints
	22, // 5: optimizer.v1.OptimizeResponse.status:type_name -> optimizer.v1.ResultStatus
	23, // 6: optimizer.v1.OptimizeResponse.routes:type_name -> optimizer.v1.RoutePlan
	24, // 7: optimizer.v1.OptimizeResponse.warnings:type_name -> optimizer.v1.Warning
	25, // 8: optimizer.v1.OptimizeResponse.conflicts:type_name -> optimizer.v1.Conflict
	26, // 9: optimizer.v1.OptimizeResponse.data:type_name -> optimizer.v1.DataFreshness
	0,  // 10: optimizer.v1.VisitExecution.status:type_name -> optimizer.v1.ExecutionStatus
	19, // 11: optimizer.v1.VisitExecution.actual_started_at:type_name -> google.protobuf.Timestamp
	19, // 12: optimizer.v1.VisitExecution.actual_ended_at:type_name -> google.protobuf.Timestamp
	1,  // 13: optimizer.v1.DelayTrigger.mode:type_name -> optimizer.v1.DelayMode
	19, // 14: optimizer.v1.DelayTrigger.effective_start_at:type_name -> google.protobuf.Timestamp
	20, // 15: optimizer.v1.DelayTrigger.position:type_name -> optimizer.v1.Coordinate
	2,  // 16: optimizer.v1.DelayTrigger.position_source:type_name -> optimizer.v1.PositionSource
	3,  // 17: optimizer.v1.RemovalTrigger.mode:type_name -> optimizer.v1.RemovalMode
	4,  // 18: optimizer.v1.PinTrigger.kind:type_name -> optimizer.v1.PinKind
	23, // 19: optimizer.v1.RecomputeRequest.base_plan:type_name -> optimizer.v1.RoutePlan
	21, // 20: optimizer.v1.RecomputeRequest.constraints:type_name -> optimizer.v1.RouteConstraints
	9,  // 21: optimizer.v1.RecomputeRequest.history:type_name -> optimizer.v1.VisitExecution
	10, // 22: optimizer.v1.RecomputeRequest.delay:type_name -> optimizer.v1.DelayTrigger
	11, // 23: optimizer.v1.RecomputeRequest.cancellation:type_name -> optimizer.v1.CancellationTrigger
	12, // 24: optimizer.v1.RecomputeRequest.removal:type_name -> optimizer.v1.RemovalTrigger
	13, // 25: optimizer.v1.RecomputeRequest.pin:type_name -> optimizer.v1.PinTrigger
	27, // 26: optimizer.v1.CostChange.before:type_name -> optimizer.v1.Money
	27, // 27: optimizer.v1.CostChange.after:type_name -> optimizer.v1.Money
	28, // 28: optimizer.v1.VerificationChange.before:type_name -> optimizer.v1.VerificationStatus
	28, // 29: optimizer.v1.VerificationChange.after:type_name -> optimizer.v1.VerificationStatus
	6,  // 30: optimizer.v1.RouteChange.kind:type_name -> optimizer.v1.RouteChangeKind
	29, // 31: optimizer.v1.RouteChange.scope:type_name -> optimizer.v1.TargetScope
	15, // 32: optimizer.v1.RouteChange.cost:type_name -> optimizer.v1.CostChange
	16, // 33: optimizer.v1.RouteChange.verification:type_name -> optimizer.v1.VerificationChange
	5,  // 34: optimizer.v1.RecomputeResponse.status:type_name -> optimizer.v1.RecomputeStatus
	23, // 35: optimizer.v1.RecomputeResponse.candidate:type_name -> optimizer.v1.RoutePlan
	17, // 36: optimizer.v1.RecomputeResponse.changes:type_name -> optimizer.v1.RouteChange
	25, // 37: optimizer.v1.RecomputeResponse.conflicts:type_name -> optimizer.v1.Conflict
	26, // 38: optimizer.v1.RecomputeResponse.data:type_name -> optimizer.v1.DataFreshness
	7,  // 39: optimizer.v1.OptimizerService.Optimize:input_type -> optimizer.v1.OptimizeRequest
	14, // 40: optimizer.v1.OptimizerService.Recompute:input_type -> optimizer.v1.RecomputeRequest
	8,  // 41: optimizer.v1.OptimizerService.Optimize:output_type -> optimizer.v1.OptimizeResponse
	18, // 42: optimizer.v1.OptimizerService.Recompute:output_type -> optimizer.v1.RecomputeResponse
	41, // [41:43] is the sub-list for method output_type
	39, // [39:41] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_optimizer_v1_optimizer_proto_init() }
func file_optimizer_v1_optimizer_proto_init() {
	if File_optimizer_v1_optimizer_proto != nil {
		return
	}
	file_optimizer_v1_constraints_proto_init()
	file_optimizer_v1_plan_proto_init()
	file_optimizer_v1_values_proto_init()
	file_optimizer_v1_optimizer_proto_msgTypes[7].OneofWrappers = []any{
		(*RecomputeRequest_Delay)(nil),
		(*RecomputeRequest_Cancellation)(nil),
		(*RecomputeRequest_Removal)(nil),
		(*RecomputeRequest_Pin)(nil),
	}
	file_optimizer_v1_optimizer_proto_msgTypes[10].OneofWrappers = []any{
		(*RouteChange_TimeShiftSeconds)(nil),
		(*RouteChange_Cost)(nil),
		(*RouteChange_ParticipationAction)(nil),
		(*RouteChange_Verification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_v1_optimizer_proto_rawDesc), len(file_optimizer_v1_optimizer_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimizer_v1_optimizer_proto_goTypes,
		DependencyIndexes: file_optimizer_v1_optimizer_proto_depIdxs,
		EnumInfos:         file_optimizer_v1_optimizer_proto_enumTypes,
		MessageInfos:      file_optimizer_v1_optimizer_proto_msgTypes,
	}.Build()
	File_optimizer_v1_optimizer_proto = out.File
	file_optimizer_v1_optimizer_proto_goTypes = nil
	file_optimizer_v1_optimizer_proto_depIdxs = nil
}
