// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: optimizer/v1/optimizer.proto

package optimizerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizerService_Optimize_FullMethodName  = "/optimizer.v1.OptimizerService/Optimize"
	OptimizerService_Recompute_FullMethodName = "/optimizer.v1.OptimizerService/Recompute"
)

// OptimizerServiceClient is the client API for OptimizerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Stateless route computation. The caller propagates x-request-id and trace context in
// metadata and sets the deadline. Infeasibility is a result status, never an RPC error.
type OptimizerServiceClient interface {
	Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error)
	Recompute(ctx context.Context, in *RecomputeRequest, opts ...grpc.CallOption) (*RecomputeResponse, error)
}

type optimizerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizerServiceClient(cc grpc.ClientConnInterface) OptimizerServiceClient {
	return &optimizerServiceClient{cc}
}

func (c *optimizerServiceClient) Optimize(ctx context.Context, in *OptimizeRequest, opts ...grpc.CallOption) (*OptimizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizeResponse)
	err := c.cc.Invoke(ctx, OptimizerService_Optimize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizerServiceClient) Recompute(ctx context.Context, in *RecomputeRequest, opts ...grpc.CallOption) (*RecomputeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecomputeResponse)
	err := c.cc.Invoke(ctx, OptimizerService_Recompute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizerServiceServer is the server API for OptimizerService service.
// All implementations must embed UnimplementedOptimizerServiceServer
// for forward compatibility.
//
// Stateless route computation. The caller propagates x-request-id and trace context in
// metadata and sets the deadline. Infeasibility is a result status, never an RPC error.
type OptimizerServiceServer interface {
	Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error)
	Recompute(context.Context, *RecomputeRequest) (*RecomputeResponse, error)
	mustEmbedUnimplementedOptimizerServiceServer()
}

// UnimplementedOptimizerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizerServiceServer struct{}

func (UnimplementedOptimizerServiceServer) Optimize(context.Context, *OptimizeRequest) (*OptimizeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Optimize not implemented")
}
func (UnimplementedOptimizerServiceServer) Recompute(context.Context, *RecomputeRequest) (*RecomputeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recompute not implemented")
}
func (UnimplementedOptimizerServiceServer) mustEmbedUnimplementedOptimizerServiceServer() {}
func (UnimplementedOptimizerServiceServer) testEmbeddedByValue()                          {}

// UnsafeOptimizerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizerServiceServer will
// result in compilation errors.
type UnsafeOptimizerServiceServer interface {
	mustEmbedUnimplementedOptimizerServiceServer()
}

func RegisterOptimizerServiceServer(s grpc.ServiceRegistrar, srv OptimizerServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizerService_ServiceDesc, srv)
}

func _OptimizerService_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_Optimize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).Optimize(ctx, req.(*OptimizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizerService_Recompute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecomputeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizerServiceServer).Recompute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizerService_Recompute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizerServiceServer).Recompute(ctx, req.(*RecomputeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizerService_ServiceDesc is the grpc.ServiceDesc for OptimizerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "optimizer.v1.OptimizerService",
	HandlerType: (*OptimizerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Optimize",
			Handler:    _OptimizerService_Optimize_Handler,
		},
		{
			MethodName: "Recompute",
			Handler:    _OptimizerService_Recompute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optimizer/v1/optimizer.proto",
}
