// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: optimizer/v1/plan.proto

package optimizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResultStatus int32

const (
	ResultStatus_RESULT_STATUS_UNSPECIFIED ResultStatus = 0
	ResultStatus_RESULT_STATUS_READY       ResultStatus = 1
	// Feasible only under unknown conditions the user explicitly accepted.
	ResultStatus_RESULT_STATUS_PARTIAL           ResultStatus = 2
	ResultStatus_RESULT_STATUS_NO_FEASIBLE_ROUTE ResultStatus = 3
	ResultStatus_RESULT_STATUS_CONFLICT          ResultStatus = 4
)

// Enum value maps for ResultStatus.
var (
	ResultStatus_name = map[int32]string{
		0: "RESULT_STATUS_UNSPECIFIED",
		1: "RESULT_STATUS_READY",
		2: "RESULT_STATUS_PARTIAL",
		3: "RESULT_STATUS_NO_FEASIBLE_ROUTE",
		4: "RESULT_STATUS_CONFLICT",
	}
	ResultStatus_value = map[string]int32{
		"RESULT_STATUS_UNSPECIFIED":       0,
		"RESULT_STATUS_READY":             1,
		"RESULT_STATUS_PARTIAL":           2,
		"RESULT_STATUS_NO_FEASIBLE_ROUTE": 3,
		"RESULT_STATUS_CONFLICT":          4,
	}
)

func (x ResultStatus) Enum() *ResultStatus {
	p := new(ResultStatus)
	*p = x
	return p
}

func (x ResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[0].Descriptor()
}

func (ResultStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[0]
}

func (x ResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResultStatus.Descriptor instead.
func (ResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{0}
}

type AvailabilityStatus int32

const (
	AvailabilityStatus_AVAILABILITY_STATUS_UNSPECIFIED           AvailabilityStatus = 0
	AvailabilityStatus_AVAILABILITY_STATUS_AVAILABLE             AvailabilityStatus = 1
	AvailabilityStatus_AVAILABILITY_STATUS_REGISTRATION_REQUIRED AvailabilityStatus = 2
	AvailabilityStatus_AVAILABILITY_STATUS_SOLD_OUT              AvailabilityStatus = 3
	AvailabilityStatus_AVAILABILITY_STATUS_CANCELLED             AvailabilityStatus = 4
	AvailabilityStatus_AVAILABILITY_STATUS_UNKNOWN               AvailabilityStatus = 5
)

// Enum value maps for AvailabilityStatus.
var (
	AvailabilityStatus_name = map[int32]string{
		0: "AVAILABILITY_STATUS_UNSPECIFIED",
		1: "AVAILABILITY_STATUS_AVAILABLE",
		2: "AVAILABILITY_STATUS_REGISTRATION_REQUIRED",
		3: "AVAILABILITY_STATUS_SOLD_OUT",
		4: "AVAILABILITY_STATUS_CANCELLED",
		5: "AVAILABILITY_STATUS_UNKNOWN",
	}
	AvailabilityStatus_value = map[string]int32{
		"AVAILABILITY_STATUS_UNSPECIFIED":           0,
		"AVAILABILITY_STATUS_AVAILABLE":             1,
		"AVAILABILITY_STATUS_REGISTRATION_REQUIRED": 2,
		"AVAILABILITY_STATUS_SOLD_OUT":              3,
		"AVAILABILITY_STATUS_CANCELLED":             4,
		"AVAILABILITY_STATUS_UNKNOWN":               5,
	}
)

func (x AvailabilityStatus) Enum() *AvailabilityStatus {
	p := new(AvailabilityStatus)
	*p = x
	return p
}

func (x AvailabilityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[1].Descriptor()
}

func (AvailabilityStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[1]
}

func (x AvailabilityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailabilityStatus.Descriptor instead.
func (AvailabilityStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{1}
}

type BudgetConclusion int32

const (
	BudgetConclusion_BUDGET_CONCLUSION_UNSPECIFIED    BudgetConclusion = 0
	BudgetConclusion_BUDGET_CONCLUSION_NOT_APPLICABLE BudgetConclusion = 1
	BudgetConclusion_BUDGET_CONCLUSION_SATISFIED      BudgetConclusion = 2
	BudgetConclusion_BUDGET_CONCLUSION_VIOLATED       BudgetConclusion = 3
	BudgetConclusion_BUDGET_CONCLUSION_UNKNOWN        BudgetConclusion = 4
)

// Enum value maps for BudgetConclusion.
var (
	BudgetConclusion_name = map[int32]string{
		0: "BUDGET_CONCLUSION_UNSPECIFIED",
		1: "BUDGET_CONCLUSION_NOT_APPLICABLE",
		2: "BUDGET_CONCLUSION_SATISFIED",
		3: "BUDGET_CONCLUSION_VIOLATED",
		4: "BUDGET_CONCLUSION_UNKNOWN",
	}
	BudgetConclusion_value = map[string]int32{
		"BUDGET_CONCLUSION_UNSPECIFIED":    0,
		"BUDGET_CONCLUSION_NOT_APPLICABLE": 1,
		"BUDGET_CONCLUSION_SATISFIED":      2,
		"BUDGET_CONCLUSION_VIOLATED":       3,
		"BUDGET_CONCLUSION_UNKNOWN":        4,
	}
)

func (x BudgetConclusion) Enum() *BudgetConclusion {
	p := new(BudgetConclusion)
	*p = x
	return p
}

func (x BudgetConclusion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BudgetConclusion) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[2].Descriptor()
}

func (BudgetConclusion) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[2]
}

func (x BudgetConclusion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BudgetConclusion.Descriptor instead.
func (BudgetConclusion) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{2}
}

type ParticipationEvidence int32

const (
	ParticipationEvidence_PARTICIPATION_EVIDENCE_UNSPECIFIED ParticipationEvidence = 0
	ParticipationEvidence_PARTICIPATION_EVIDENCE_NONE        ParticipationEvidence = 1
	ParticipationEvidence_PARTICIPATION_EVIDENCE_USER        ParticipationEvidence = 2
	ParticipationEvidence_PARTICIPATION_EVIDENCE_PROVIDER    ParticipationEvidence = 3
)

// Enum value maps for ParticipationEvidence.
var (
	ParticipationEvidence_name = map[int32]string{
		0: "PARTICIPATION_EVIDENCE_UNSPECIFIED",
		1: "PARTICIPATION_EVIDENCE_NONE",
		2: "PARTICIPATION_EVIDENCE_USER",
		3: "PARTICIPATION_EVIDENCE_PROVIDER",
	}
	ParticipationEvidence_value = map[string]int32{
		"PARTICIPATION_EVIDENCE_UNSPECIFIED": 0,
		"PARTICIPATION_EVIDENCE_NONE":        1,
		"PARTICIPATION_EVIDENCE_USER":        2,
		"PARTICIPATION_EVIDENCE_PROVIDER":    3,
	}
)

func (x ParticipationEvidence) Enum() *ParticipationEvidence {
	p := new(ParticipationEvidence)
	*p = x
	return p
}

func (x ParticipationEvidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipationEvidence) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[3].Descriptor()
}

func (ParticipationEvidence) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[3]
}

func (x ParticipationEvidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipationEvidence.Descriptor instead.
func (ParticipationEvidence) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{3}
}

type ConstraintStrength int32

const (
	ConstraintStrength_CONSTRAINT_STRENGTH_UNSPECIFIED ConstraintStrength = 0
	ConstraintStrength_CONSTRAINT_STRENGTH_HARD        ConstraintStrength = 1
	ConstraintStrength_CONSTRAINT_STRENGTH_SOFT        ConstraintStrength = 2
)

// Enum value maps for ConstraintStrength.
var (
	ConstraintStrength_name = map[int32]string{
		0: "CONSTRAINT_STRENGTH_UNSPECIFIED",
		1: "CONSTRAINT_STRENGTH_HARD",
		2: "CONSTRAINT_STRENGTH_SOFT",
	}
	ConstraintStrength_value = map[string]int32{
		"CONSTRAINT_STRENGTH_UNSPECIFIED": 0,
		"CONSTRAINT_STRENGTH_HARD":        1,
		"CONSTRAINT_STRENGTH_SOFT":        2,
	}
)

func (x ConstraintStrength) Enum() *ConstraintStrength {
	p := new(ConstraintStrength)
	*p = x
	return p
}

func (x ConstraintStrength) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintStrength) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[4].Descriptor()
}

func (ConstraintStrength) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[4]
}

func (x ConstraintStrength) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintStrength.Descriptor instead.
func (ConstraintStrength) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{4}
}

type ConstraintOutcome int32

const (
	ConstraintOutcome_CONSTRAINT_OUTCOME_UNSPECIFIED ConstraintOutcome = 0
	ConstraintOutcome_CONSTRAINT_OUTCOME_SATISFIED   ConstraintOutcome = 1
	ConstraintOutcome_CONSTRAINT_OUTCOME_CONDITIONAL ConstraintOutcome = 2
)

// Enum value maps for ConstraintOutcome.
var (
	ConstraintOutcome_name = map[int32]string{
		0: "CONSTRAINT_OUTCOME_UNSPECIFIED",
		1: "CONSTRAINT_OUTCOME_SATISFIED",
		2: "CONSTRAINT_OUTCOME_CONDITIONAL",
	}
	ConstraintOutcome_value = map[string]int32{
		"CONSTRAINT_OUTCOME_UNSPECIFIED": 0,
		"CONSTRAINT_OUTCOME_SATISFIED":   1,
		"CONSTRAINT_OUTCOME_CONDITIONAL": 2,
	}
)

func (x ConstraintOutcome) Enum() *ConstraintOutcome {
	p := new(ConstraintOutcome)
	*p = x
	return p
}

func (x ConstraintOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[5].Descriptor()
}

func (ConstraintOutcome) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[5]
}

func (x ConstraintOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintOutcome.Descriptor instead.
func (ConstraintOutcome) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{5}
}

type VisitKind int32

const (
	VisitKind_VISIT_KIND_UNSPECIFIED VisitKind = 0
	VisitKind_VISIT_KIND_VISIT       VisitKind = 1
	VisitKind_VISIT_KIND_FREE_TIME   VisitKind = 2
)

// Enum value maps for VisitKind.
var (
	VisitKind_name = map[int32]string{
		0: "VISIT_KIND_UNSPECIFIED",
		1: "VISIT_KIND_VISIT",
		2: "VISIT_KIND_FREE_TIME",
	}
	VisitKind_value = map[string]int32{
		"VISIT_KIND_UNSPECIFIED": 0,
		"VISIT_KIND_VISIT":       1,
		"VISIT_KIND_FREE_TIME":   2,
	}
)

func (x VisitKind) Enum() *VisitKind {
	p := new(VisitKind)
	*p = x
	return p
}

func (x VisitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[6].Descriptor()
}

func (VisitKind) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[6]
}

func (x VisitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisitKind.Descriptor instead.
func (VisitKind) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{6}
}

type LegEndpointKind int32

const (
	LegEndpointKind_LEG_ENDPOINT_KIND_UNSPECIFIED LegEndpointKind = 0
	LegEndpointKind_LEG_ENDPOINT_KIND_ORIGIN      LegEndpointKind = 1
	LegEndpointKind_LEG_ENDPOINT_KIND_VISIT       LegEndpointKind = 2
	LegEndpointKind_LEG_ENDPOINT_KIND_DESTINATION LegEndpointKind = 3
)

// Enum value maps for LegEndpointKind.
var (
	LegEndpointKind_name = map[int32]string{
		0: "LEG_ENDPOINT_KIND_UNSPECIFIED",
		1: "LEG_ENDPOINT_KIND_ORIGIN",
		2: "LEG_ENDPOINT_KIND_VISIT",
		3: "LEG_ENDPOINT_KIND_DESTINATION",
	}
	LegEndpointKind_value = map[string]int32{
		"LEG_ENDPOINT_KIND_UNSPECIFIED": 0,
		"LEG_ENDPOINT_KIND_ORIGIN":      1,
		"LEG_ENDPOINT_KIND_VISIT":       2,
		"LEG_ENDPOINT_KIND_DESTINATION": 3,
	}
)

func (x LegEndpointKind) Enum() *LegEndpointKind {
	p := new(LegEndpointKind)
	*p = x
	return p
}

func (x LegEndpointKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LegEndpointKind) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[7].Descriptor()
}

func (LegEndpointKind) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[7]
}

func (x LegEndpointKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LegEndpointKind.Descriptor instead.
func (LegEndpointKind) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{7}
}

type TargetScope int32

const (
	TargetScope_TARGET_SCOPE_UNSPECIFIED TargetScope = 0
	TargetScope_TARGET_SCOPE_ROUTE       TargetScope = 1
	TargetScope_TARGET_SCOPE_VISIT       TargetScope = 2
	TargetScope_TARGET_SCOPE_LEG         TargetScope = 3
)

// Enum value maps for TargetScope.
var (
	TargetScope_name = map[int32]string{
		0: "TARGET_SCOPE_UNSPECIFIED",
		1: "TARGET_SCOPE_ROUTE",
		2: "TARGET_SCOPE_VISIT",
		3: "TARGET_SCOPE_LEG",
	}
	TargetScope_value = map[string]int32{
		"TARGET_SCOPE_UNSPECIFIED": 0,
		"TARGET_SCOPE_ROUTE":       1,
		"TARGET_SCOPE_VISIT":       2,
		"TARGET_SCOPE_LEG":         3,
	}
)

func (x TargetScope) Enum() *TargetScope {
	p := new(TargetScope)
	*p = x
	return p
}

func (x TargetScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetScope) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_plan_proto_enumTypes[8].Descriptor()
}

func (TargetScope) Type() protoreflect.EnumType {
	return &file_optimizer_v1_plan_proto_enumTypes[8]
}

func (x TargetScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetScope.Descriptor instead.
func (TargetScope) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{8}
}

type CatalogSnapshot struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PlaceId             []byte                 `protobuf:"bytes,1,opt,name=place_id,json=placeId,proto3" json:"place_id,omitempty"`
	EntranceId          []byte                 `protobuf:"bytes,2,opt,name=entrance_id,json=entranceId,proto3" json:"entrance_id,omitempty"`
	EventId             []byte                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId           []byte                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title               string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Category            Category               `protobuf:"varint,6,opt,name=category,proto3,enum=optimizer.v1.Category" json:"category,omitempty"`
	InterestMask        uint64                 `protobuf:"varint,7,opt,name=interest_mask,json=interestMask,proto3" json:"interest_mask,omitempty"`
	Availability        AvailabilityStatus     `protobuf:"varint,8,opt,name=availability,proto3,enum=optimizer.v1.AvailabilityStatus" json:"availability,omitempty"`
	RegistrationDetails string                 `protobuf:"bytes,9,opt,name=registration_details,json=registrationDetails,proto3" json:"registration_details,omitempty"`
	AgeRequirements     string                 `protobuf:"bytes,10,opt,name=age_requirements,json=ageRequirements,proto3" json:"age_requirements,omitempty"`
	SessionStartsAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=session_starts_at,json=sessionStartsAt,proto3" json:"session_starts_at,omitempty"`
	SessionEndsAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=session_ends_at,json=sessionEndsAt,proto3" json:"session_ends_at,omitempty"`
	SessionVersion      string                 `protobuf:"bytes,13,opt,name=session_version,json=sessionVersion,proto3" json:"session_version,omitempty"`
	DataMode            DataMode               `protobuf:"varint,14,opt,name=data_mode,json=dataMode,proto3,enum=optimizer.v1.DataMode" json:"data_mode,omitempty"`
	Provenance          *Provenance            `protobuf:"bytes,15,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CatalogSnapshot) Reset() {
	*x = CatalogSnapshot{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogSnapshot) ProtoMessage() {}

func (x *CatalogSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogSnapshot.ProtoReflect.Descriptor instead.
func (*CatalogSnapshot) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogSnapshot) GetPlaceId() []byte {
	if x != nil {
		return x.PlaceId
	}
	return nil
}

func (x *CatalogSnapshot) GetEntranceId() []byte {
	if x != nil {
		return x.EntranceId
	}
	return nil
}

func (x *CatalogSnapshot) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *CatalogSnapshot) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *CatalogSnapshot) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CatalogSnapshot) GetCategory() Category {
	if x != nil {
		return x.Category
	}
	return Category_CATEGORY_UNSPECIFIED
}

func (x *CatalogSnapshot) GetInterestMask() uint64 {
	if x != nil {
		return x.InterestMask
	}
	return 0
}

func (x *CatalogSnapshot) GetAvailability() AvailabilityStatus {
	if x != nil {
		return x.Availability
	}
	return AvailabilityStatus_AVAILABILITY_STATUS_UNSPECIFIED
}

func (x *CatalogSnapshot) GetRegistrationDetails() string {
	if x != nil {
		return x.RegistrationDetails
	}
	return ""
}

func (x *CatalogSnapshot) GetAgeRequirements() string {
	if x != nil {
		return x.AgeRequirements
	}
	return ""
}

func (x *CatalogSnapshot) GetSessionStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionStartsAt
	}
	return nil
}

func (x *CatalogSnapshot) GetSessionEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionEndsAt
	}
	return nil
}

func (x *CatalogSnapshot) GetSessionVersion() string {
	if x != nil {
		return x.SessionVersion
	}
	return ""
}

func (x *CatalogSnapshot) GetDataMode() DataMode {
	if x != nil {
		return x.DataMode
	}
	return DataMode_DATA_MODE_UNSPECIFIED
}

func (x *CatalogSnapshot) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type UnknownCostComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownCostComponent) Reset() {
	*x = UnknownCostComponent{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownCostComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownCostComponent) ProtoMessage() {}

func (x *UnknownCostComponent) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownCostComponent.ProtoReflect.Descriptor instead.
func (*UnknownCostComponent) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{1}
}

func (x *UnknownCostComponent) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UnknownCostComponent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CostSnapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PriceOfferId []byte                 `protobuf:"bytes,1,opt,name=price_offer_id,json=priceOfferId,proto3" json:"price_offer_id,omitempty"`
	Audience     string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	Price        *Price                 `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Absent when the personal share cannot be determined.
	PersonalAmount    *Money                  `protobuf:"bytes,4,opt,name=personal_amount,json=personalAmount,proto3" json:"personal_amount,omitempty"`
	ProgramAmount     *Money                  `protobuf:"bytes,5,opt,name=program_amount,json=programAmount,proto3" json:"program_amount,omitempty"`
	UnknownComponents []*UnknownCostComponent `protobuf:"bytes,6,rep,name=unknown_components,json=unknownComponents,proto3" json:"unknown_components,omitempty"`
	Provenance        *Provenance             `protobuf:"bytes,7,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CostSnapshot) Reset() {
	*x = CostSnapshot{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostSnapshot) ProtoMessage() {}

func (x *CostSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostSnapshot.ProtoReflect.Descriptor instead.
func (*CostSnapshot) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{2}
}

func (x *CostSnapshot) GetPriceOfferId() []byte {
	if x != nil {
		return x.PriceOfferId
	}
	return nil
}

func (x *CostSnapshot) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *CostSnapshot) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CostSnapshot) GetPersonalAmount() *Money {
	if x != nil {
		return x.PersonalAmount
	}
	return nil
}

func (x *CostSnapshot) GetProgramAmount() *Money {
	if x != nil {
		return x.ProgramAmount
	}
	return nil
}

func (x *CostSnapshot) GetUnknownComponents() []*UnknownCostComponent {
	if x != nil {
		return x.UnknownComponents
	}
	return nil
}

func (x *CostSnapshot) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type CostSummary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Includes known personal transport costs.
	KnownPersonal     *Money                  `protobuf:"bytes,1,opt,name=known_personal,json=knownPersonal,proto3" json:"known_personal,omitempty"`
	KnownTransport    *Money                  `protobuf:"bytes,2,opt,name=known_transport,json=knownTransport,proto3" json:"known_transport,omitempty"`
	ProgramAmount     *Money                  `protobuf:"bytes,3,opt,name=program_amount,json=programAmount,proto3" json:"program_amount,omitempty"`
	TotalLower        *Money                  `protobuf:"bytes,4,opt,name=total_lower,json=totalLower,proto3" json:"total_lower,omitempty"`
	TotalUpper        *Money                  `protobuf:"bytes,5,opt,name=total_upper,json=totalUpper,proto3" json:"total_upper,omitempty"`
	UnknownComponents []*UnknownCostComponent `protobuf:"bytes,6,rep,name=unknown_components,json=unknownComponents,proto3" json:"unknown_components,omitempty"`
	BudgetConclusion  BudgetConclusion        `protobuf:"varint,7,opt,name=budget_conclusion,json=budgetConclusion,proto3,enum=optimizer.v1.BudgetConclusion" json:"budget_conclusion,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CostSummary) Reset() {
	*x = CostSummary{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CostSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostSummary) ProtoMessage() {}

func (x *CostSummary) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostSummary.ProtoReflect.Descriptor instead.
func (*CostSummary) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{3}
}

func (x *CostSummary) GetKnownPersonal() *Money {
	if x != nil {
		return x.KnownPersonal
	}
	return nil
}

func (x *CostSummary) GetKnownTransport() *Money {
	if x != nil {
		return x.KnownTransport
	}
	return nil
}

func (x *CostSummary) GetProgramAmount() *Money {
	if x != nil {
		return x.ProgramAmount
	}
	return nil
}

func (x *CostSummary) GetTotalLower() *Money {
	if x != nil {
		return x.TotalLower
	}
	return nil
}

func (x *CostSummary) GetTotalUpper() *Money {
	if x != nil {
		return x.TotalUpper
	}
	return nil
}

func (x *CostSummary) GetUnknownComponents() []*UnknownCostComponent {
	if x != nil {
		return x.UnknownComponents
	}
	return nil
}

func (x *CostSummary) GetBudgetConclusion() BudgetConclusion {
	if x != nil {
		return x.BudgetConclusion
	}
	return BudgetConclusion_BUDGET_CONCLUSION_UNSPECIFIED
}

type ParticipationSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ParticipationStatus    `protobuf:"varint,1,opt,name=status,proto3,enum=optimizer.v1.ParticipationStatus" json:"status,omitempty"`
	Evidence      ParticipationEvidence  `protobuf:"varint,2,opt,name=evidence,proto3,enum=optimizer.v1.ParticipationEvidence" json:"evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipationSnapshot) Reset() {
	*x = ParticipationSnapshot{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipationSnapshot) ProtoMessage() {}

func (x *ParticipationSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipationSnapshot.ProtoReflect.Descriptor instead.
func (*ParticipationSnapshot) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{4}
}

func (x *ParticipationSnapshot) GetStatus() ParticipationStatus {
	if x != nil {
		return x.Status
	}
	return ParticipationStatus_PARTICIPATION_STATUS_UNSPECIFIED
}

func (x *ParticipationSnapshot) GetEvidence() ParticipationEvidence {
	if x != nil {
		return x.Evidence
	}
	return ParticipationEvidence_PARTICIPATION_EVIDENCE_UNSPECIFIED
}

type AppliedConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Strength      ConstraintStrength     `protobuf:"varint,2,opt,name=strength,proto3,enum=optimizer.v1.ConstraintStrength" json:"strength,omitempty"`
	Outcome       ConstraintOutcome      `protobuf:"varint,3,opt,name=outcome,proto3,enum=optimizer.v1.ConstraintOutcome" json:"outcome,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedConstraint) Reset() {
	*x = AppliedConstraint{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedConstraint) ProtoMessage() {}

func (x *AppliedConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedConstraint.ProtoReflect.Descriptor instead.
func (*AppliedConstraint) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{5}
}

func (x *AppliedConstraint) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AppliedConstraint) GetStrength() ConstraintStrength {
	if x != nil {
		return x.Strength
	}
	return ConstraintStrength_CONSTRAINT_STRENGTH_UNSPECIFIED
}

func (x *AppliedConstraint) GetOutcome() ConstraintOutcome {
	if x != nil {
		return x.Outcome
	}
	return ConstraintOutcome_CONSTRAINT_OUTCOME_UNSPECIFIED
}

func (x *AppliedConstraint) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RouteStep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Existing visits keep their identifier; new visits get a fresh UUIDv7 from the optimizer.
	VisitId            []byte                 `protobuf:"bytes,1,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	Kind               VisitKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=optimizer.v1.VisitKind" json:"kind,omitempty"`
	Position           uint32                 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	ArrivalAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=arrival_at,json=arrivalAt,proto3" json:"arrival_at,omitempty"`
	VisitStartAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=visit_start_at,json=visitStartAt,proto3" json:"visit_start_at,omitempty"`
	VisitEndAt         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=visit_end_at,json=visitEndAt,proto3" json:"visit_end_at,omitempty"`
	DepartureAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=departure_at,json=departureAt,proto3" json:"departure_at,omitempty"`
	MinDurationSeconds int64                  `protobuf:"varint,8,opt,name=min_duration_seconds,json=minDurationSeconds,proto3" json:"min_duration_seconds,omitempty"`
	Pinned             bool                   `protobuf:"varint,9,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Obligation         bool                   `protobuf:"varint,10,opt,name=obligation,proto3" json:"obligation,omitempty"`
	Participation      *ParticipationSnapshot `protobuf:"bytes,11,opt,name=participation,proto3" json:"participation,omitempty"`
	// Present for visits and absent for free time.
	Catalog            *CatalogSnapshot     `protobuf:"bytes,12,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Cost               *CostSnapshot        `protobuf:"bytes,13,opt,name=cost,proto3" json:"cost,omitempty"`
	AppliedConstraints []*AppliedConstraint `protobuf:"bytes,14,rep,name=applied_constraints,json=appliedConstraints,proto3" json:"applied_constraints,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouteStep) Reset() {
	*x = RouteStep{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStep) ProtoMessage() {}

func (x *RouteStep) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStep.ProtoReflect.Descriptor instead.
func (*RouteStep) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{6}
}

func (x *RouteStep) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *RouteStep) GetKind() VisitKind {
	if x != nil {
		return x.Kind
	}
	return VisitKind_VISIT_KIND_UNSPECIFIED
}

func (x *RouteStep) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RouteStep) GetArrivalAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalAt
	}
	return nil
}

func (x *RouteStep) GetVisitStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitStartAt
	}
	return nil
}

func (x *RouteStep) GetVisitEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VisitEndAt
	}
	return nil
}

func (x *RouteStep) GetDepartureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureAt
	}
	return nil
}

func (x *RouteStep) GetMinDurationSeconds() int64 {
	if x != nil {
		return x.MinDurationSeconds
	}
	return 0
}

func (x *RouteStep) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *RouteStep) GetObligation() bool {
	if x != nil {
		return x.Obligation
	}
	return false
}

func (x *RouteStep) GetParticipation() *ParticipationSnapshot {
	if x != nil {
		return x.Participation
	}
	return nil
}

func (x *RouteStep) GetCatalog() *CatalogSnapshot {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *RouteStep) GetCost() *CostSnapshot {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *RouteStep) GetAppliedConstraints() []*AppliedConstraint {
	if x != nil {
		return x.AppliedConstraints
	}
	return nil
}

type LegEvidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Limitations   []string               `protobuf:"bytes,5,rep,name=limitations,proto3" json:"limitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LegEvidence) Reset() {
	*x = LegEvidence{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LegEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LegEvidence) ProtoMessage() {}

func (x *LegEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LegEvidence.ProtoReflect.Descriptor instead.
func (*LegEvidence) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{7}
}

func (x *LegEvidence) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LegEvidence) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LegEvidence) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *LegEvidence) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *LegEvidence) GetLimitations() []string {
	if x != nil {
		return x.Limitations
	}
	return nil
}

type RouteLeg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Position       uint32                 `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	FromKind       LegEndpointKind        `protobuf:"varint,2,opt,name=from_kind,json=fromKind,proto3,enum=optimizer.v1.LegEndpointKind" json:"from_kind,omitempty"`
	ToKind         LegEndpointKind        `protobuf:"varint,3,opt,name=to_kind,json=toKind,proto3,enum=optimizer.v1.LegEndpointKind" json:"to_kind,omitempty"`
	FromVisitId    []byte                 `protobuf:"bytes,4,opt,name=from_visit_id,json=fromVisitId,proto3" json:"from_visit_id,omitempty"`
	ToVisitId      []byte                 `protobuf:"bytes,5,opt,name=to_visit_id,json=toVisitId,proto3" json:"to_visit_id,omitempty"`
	DepartureAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=departure_at,json=departureAt,proto3" json:"departure_at,omitempty"`
	ArrivalAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=arrival_at,json=arrivalAt,proto3" json:"arrival_at,omitempty"`
	Mode           string                 `protobuf:"bytes,8,opt,name=mode,proto3" json:"mode,omitempty"`
	DistanceMeters *float64               `protobuf:"fixed64,9,opt,name=distance_meters,json=distanceMeters,proto3,oneof" json:"distance_meters,omitempty"`
	// Geometry never raises the verification status.
	Geometry      []*Coordinate      `protobuf:"bytes,10,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Verification  VerificationStatus `protobuf:"varint,11,opt,name=verification,proto3,enum=optimizer.v1.VerificationStatus" json:"verification,omitempty"`
	Evidence      *LegEvidence       `protobuf:"bytes,12,opt,name=evidence,proto3" json:"evidence,omitempty"`
	Cost          *CostSnapshot      `protobuf:"bytes,13,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteLeg) Reset() {
	*x = RouteLeg{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteLeg) ProtoMessage() {}

func (x *RouteLeg) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteLeg.ProtoReflect.Descriptor instead.
func (*RouteLeg) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{8}
}

func (x *RouteLeg) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *RouteLeg) GetFromKind() LegEndpointKind {
	if x != nil {
		return x.FromKind
	}
	return LegEndpointKind_LEG_ENDPOINT_KIND_UNSPECIFIED
}

func (x *RouteLeg) GetToKind() LegEndpointKind {
	if x != nil {
		return x.ToKind
	}
	return LegEndpointKind_LEG_ENDPOINT_KIND_UNSPECIFIED
}

func (x *RouteLeg) GetFromVisitId() []byte {
	if x != nil {
		return x.FromVisitId
	}
	return nil
}

func (x *RouteLeg) GetToVisitId() []byte {
	if x != nil {
		return x.ToVisitId
	}
	return nil
}

func (x *RouteLeg) GetDepartureAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureAt
	}
	return nil
}

func (x *RouteLeg) GetArrivalAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalAt
	}
	return nil
}

func (x *RouteLeg) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RouteLeg) GetDistanceMeters() float64 {
	if x != nil && x.DistanceMeters != nil {
		return *x.DistanceMeters
	}
	return 0
}

func (x *RouteLeg) GetGeometry() []*Coordinate {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *RouteLeg) GetVerification() VerificationStatus {
	if x != nil {
		return x.Verification
	}
	return VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED
}

func (x *RouteLeg) GetEvidence() *LegEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *RouteLeg) GetCost() *CostSnapshot {
	if x != nil {
		return x.Cost
	}
	return nil
}

type Warning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Scope         TargetScope            `protobuf:"varint,2,opt,name=scope,proto3,enum=optimizer.v1.TargetScope" json:"scope,omitempty"`
	VisitId       []byte                 `protobuf:"bytes,3,opt,name=visit_id,json=visitId,proto3" json:"visit_id,omitempty"`
	LegPosition   *uint32                `protobuf:"varint,4,opt,name=leg_position,json=legPosition,proto3,oneof" json:"leg_position,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Warning) Reset() {
	*x = Warning{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warning) ProtoMessage() {}

func (x *Warning) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warning.ProtoReflect.Descriptor instead.
func (*Warning) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{9}
}

func (x *Warning) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Warning) GetScope() TargetScope {
	if x != nil {
		return x.Scope
	}
	return TargetScope_TARGET_SCOPE_UNSPECIFIED
}

func (x *Warning) GetVisitId() []byte {
	if x != nil {
		return x.VisitId
	}
	return nil
}

func (x *Warning) GetLegPosition() uint32 {
	if x != nil && x.LegPosition != nil {
		return *x.LegPosition
	}
	return 0
}

func (x *Warning) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// An incompatibility between hard constraints, not a stale route revision.
type Conflict struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Code     string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	VisitIds [][]byte               `protobuf:"bytes,2,rep,name=visit_ids,json=visitIds,proto3" json:"visit_ids,omitempty"`
	// Referenced when the conflicting obligation has no visit yet.
	SessionIds    [][]byte `protobuf:"bytes,3,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	Message       string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{10}
}

func (x *Conflict) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Conflict) GetVisitIds() [][]byte {
	if x != nil {
		return x.VisitIds
	}
	return nil
}

func (x *Conflict) GetSessionIds() [][]byte {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *Conflict) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RoutePlan struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Archetype       Archetype              `protobuf:"varint,1,opt,name=archetype,proto3,enum=optimizer.v1.Archetype" json:"archetype,omitempty"`
	StartAt         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Origin          *Coordinate            `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination     *Coordinate            `protobuf:"bytes,5,opt,name=destination,proto3" json:"destination,omitempty"`
	CatalogRevision int64                  `protobuf:"varint,6,opt,name=catalog_revision,json=catalogRevision,proto3" json:"catalog_revision,omitempty"`
	Result          ResultStatus           `protobuf:"varint,7,opt,name=result,proto3,enum=optimizer.v1.ResultStatus" json:"result,omitempty"`
	Warnings        []*Warning             `protobuf:"bytes,8,rep,name=warnings,proto3" json:"warnings,omitempty"`
	Conflicts       []*Conflict            `protobuf:"bytes,9,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Cost            *CostSummary           `protobuf:"bytes,10,opt,name=cost,proto3" json:"cost,omitempty"`
	Geometry        []*Coordinate          `protobuf:"bytes,11,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Steps           []*RouteStep           `protobuf:"bytes,12,rep,name=steps,proto3" json:"steps,omitempty"`
	Legs            []*RouteLeg            `protobuf:"bytes,13,rep,name=legs,proto3" json:"legs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoutePlan) Reset() {
	*x = RoutePlan{}
	mi := &file_optimizer_v1_plan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePlan) ProtoMessage() {}

func (x *RoutePlan) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_plan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePlan.ProtoReflect.Descriptor instead.
func (*RoutePlan) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_plan_proto_rawDescGZIP(), []int{11}
}

func (x *RoutePlan) GetArchetype() Archetype {
	if x != nil {
		return x.Archetype
	}
	return Archetype_ARCHETYPE_UNSPECIFIED
}

func (x *RoutePlan) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *RoutePlan) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *RoutePlan) GetOrigin() *Coordinate {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *RoutePlan) GetDestination() *Coordinate {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *RoutePlan) GetCatalogRevision() int64 {
	if x != nil {
		return x.CatalogRevision
	}
	return 0
}

func (x *RoutePlan) GetResult() ResultStatus {
	if x != nil {
		return x.Result
	}
	return ResultStatus_RESULT_STATUS_UNSPECIFIED
}

func (x *RoutePlan) GetWarnings() []*Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *RoutePlan) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *RoutePlan) GetCost() *CostSummary {
	if x != nil {
		return x.Cost
	}
	return nil
}

func (x *RoutePlan) GetGeometry() []*Coordinate {
	if x != nil {
		return x.Geometry
	}
	return nil
}

func (x *RoutePlan) GetSteps() []*RouteStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *RoutePlan) GetLegs() []*RouteLeg {
	if x != nil {
		return x.Legs
	}
	return nil
}

var File_optimizer_v1_plan_proto protoreflect.FileDescriptor

const file_optimizer_v1_plan_proto_rawDesc = "" +
	"\n" +
	"\x17optimizer/v1/plan.proto\x12\foptimizer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19optimizer/v1/values.proto\"\xbe\x05\n" +
	"\x0fCatalogSnapshot\x12\x19\n" +
	"\bplace_id\x18\x01 \x01(\fR\aplaceId\x12\x1f\n" +
	"\ventrance_id\x18\x02 \x01(\fR\n" +
	"entranceId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\fR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\fR\tsessionId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x122\n" +
	"\bcategory\x18\x06 \x01(\x0e2\x16.optimizer.v1.CategoryR\bcategory\x12#\n" +
	"\rinterest_mask\x18\a \x01(\x04R\finterestMask\x12D\n" +
	"\favailability\x18\b \x01(\x0e2 .optimizer.v1.AvailabilityStatusR\favailability\x121\n" +
	"\x14registration_details\x18\t \x01(\tR\x13registrationDetails\x12)\n" +
	"\x10age_requirements\x18\n" +
	" \x01(\tR\x0fageRequirements\x12F\n" +
	"\x11session_starts_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x0fsessionStartsAt\x12B\n" +
	"\x0fsession_ends_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\rsessionEndsAt\x12'\n" +
	"\x0fsession_version\x18\r \x01(\tR\x0esessionVersion\x123\n" +
	"\tdata_mode\x18\x0e \x01(\x0e2\x16.optimizer.v1.DataModeR\bdataMode\x128\n" +
	"\n" +
	"provenance\x18\x0f \x01(\v2\x18.optimizer.v1.ProvenanceR\n" +
	"provenance\"D\n" +
	"\x14UnknownCostComponent\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x82\x03\n" +
	"\fCostSnapshot\x12$\n" +
	"\x0eprice_offer_id\x18\x01 \x01(\fR\fpriceOfferId\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x12)\n" +
	"\x05price\x18\x03 \x01(\v2\x13.optimizer.v1.PriceR\x05price\x12<\n" +
	"\x0fpersonal_amount\x18\x04 \x01(\v2\x13.optimizer.v1.MoneyR\x0epersonalAmount\x12:\n" +
	"\x0eprogram_amount\x18\x05 \x01(\v2\x13.optimizer.v1.MoneyR\rprogramAmount\x12Q\n" +
	"\x12unknown_components\x18\x06 \x03(\v2\".optimizer.v1.UnknownCostComponentR\x11unknownComponents\x128\n" +
	"\n" +
	"provenance\x18\a \x01(\v2\x18.optimizer.v1.ProvenanceR\n" +
	"provenance\"\xcf\x03\n" +
	"\vCostSummary\x12:\n" +
	"\x0eknown_personal\x18\x01 \x01(\v2\x13.optimizer.v1.MoneyR\rknownPersonal\x12<\n" +
	"\x0fknown_transport\x18\x02 \x01(\v2\x13.optimizer.v1.MoneyR\x0eknownTransport\x12:\n" +
	"\x0eprogram_amount\x18\x03 \x01(\v2\x13.optimizer.v1.MoneyR\rprogramAmount\x124\n" +
	"\vtotal_lower\x18\x04 \x01(\v2\x13.optimizer.v1.MoneyR\n" +
	"totalLower\x124\n" +
	"\vtotal_upper\x18\x05 \x01(\v2\x13.optimizer.v1.MoneyR\n" +
	"totalUpper\x12Q\n" +
	"\x12unknown_components\x18\x06 \x03(\v2\".optimizer.v1.UnknownCostComponentR\x11unknownComponents\x12K\n" +
	"\x11budget_conclusion\x18\a \x01(\x0e2\x1e.optimizer.v1.BudgetConclusionR\x10budgetConclusion\"\x93\x01\n" +
	"\x15ParticipationSnapshot\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.optimizer.v1.ParticipationStatusR\x06status\x12?\n" +
	"\bevidence\x18\x02 \x01(\x0e2#.optimizer.v1.ParticipationEvidenceR\bevidence\"\xba\x01\n" +
	"\x11AppliedConstraint\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12<\n" +
	"\bstrength\x18\x02 \x01(\x0e2 .optimizer.v1.ConstraintStrengthR\bstrength\x129\n" +
	"\aoutcome\x18\x03 \x01(\x0e2\x1f.optimizer.v1.ConstraintOutcomeR\aoutcome\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xd9\x05\n" +
	"\tRouteStep\x12\x19\n" +
	"\bvisit_id\x18\x01 \x01(\fR\avisitId\x12+\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x17.optimizer.v1.VisitKindR\x04kind\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\rR\bposition\x129\n" +
	"\n" +
	"arrival_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tarrivalAt\x12@\n" +
	"\x0evisit_start_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fvisitStartAt\x12<\n" +
	"\fvisit_end_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"visitEndAt\x12=\n" +
	"\fdeparture_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vdepartureAt\x120\n" +
	"\x14min_duration_seconds\x18\b \x01(\x03R\x12minDurationSeconds\x12\x16\n" +
	"\x06pinned\x18\t \x01(\bR\x06pinned\x12\x1e\n" +
	"\n" +
	"obligation\x18\n" +
	" \x01(\bR\n" +
	"obligation\x12I\n" +
	"\rparticipation\x18\v \x01(\v2#.optimizer.v1.ParticipationSnapshotR\rparticipation\x127\n" +
	"\acatalog\x18\f \x01(\v2\x1d.optimizer.v1.CatalogSnapshotR\acatalog\x12.\n" +
	"\x04cost\x18\r \x01(\v2\x1a.optimizer.v1.CostSnapshotR\x04cost\x12P\n" +
	"\x13applied_constraints\x18\x0e \x03(\v2\x1f.optimizer.v1.AppliedConstraintR\x12appliedConstraints\"\xb4\x01\n" +
	"\vLegEvidence\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12 \n" +
	"\vlimitations\x18\x05 \x03(\tR\vlimitations\"\x91\x05\n" +
	"\bRouteLeg\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\rR\bposition\x12:\n" +
	"\tfrom_kind\x18\x02 \x01(\x0e2\x1d.optimizer.v1.LegEndpointKindR\bfromKind\x126\n" +
	"\ato_kind\x18\x03 \x01(\x0e2\x1d.optimizer.v1.LegEndpointKindR\x06toKind\x12\"\n" +
	"\rfrom_visit_id\x18\x04 \x01(\fR\vfromVisitId\x12\x1e\n" +
	"\vto_visit_id\x18\x05 \x01(\fR\ttoVisitId\x12=\n" +
	"\fdeparture_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdepartureAt\x129\n" +
	"\n" +
	"arrival_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tarrivalAt\x12\x12\n" +
	"\x04mode\x18\b \x01(\tR\x04mode\x12,\n" +
	"\x0fdistance_meters\x18\t \x01(\x01H\x00R\x0edistanceMeters\x88\x01\x01\x124\n" +
	"\bgeometry\x18\n" +
	" \x03(\v2\x18.optimizer.v1.CoordinateR\bgeometry\x12D\n" +
	"\fverification\x18\v \x01(\x0e2 .optimizer.v1.VerificationStatusR\fverification\x125\n" +
	"\bevidence\x18\f \x01(\v2\x19.optimizer.v1.LegEvidenceR\bevidence\x12.\n" +
	"\x04cost\x18\r \x01(\v2\x1a.optimizer.v1.CostSnapshotR\x04costB\x12\n" +
	"\x10_distance_meters\"\xbc\x01\n" +
	"\aWarning\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12/\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x19.optimizer.v1.TargetScopeR\x05scope\x12\x19\n" +
	"\bvisit_id\x18\x03 \x01(\fR\avisitId\x12&\n" +
	"\fleg_position\x18\x04 \x01(\rH\x00R\vlegPosition\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessageB\x0f\n" +
	"\r_leg_position\"v\n" +
	"\bConflict\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tvisit_ids\x18\x02 \x03(\fR\bvisitIds\x12\x1f\n" +
	"\vsession_ids\x18\x03 \x03(\fR\n" +
	"sessionIds\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xa2\x05\n" +
	"\tRoutePlan\x125\n" +
	"\tarchetype\x18\x01 \x01(\x0e2\x17.optimizer.v1.ArchetypeR\tarchetype\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x120\n" +
	"\x06origin\x18\x04 \x01(\v2\x18.optimizer.v1.CoordinateR\x06origin\x12:\n" +
	"\vdestination\x18\x05 \x01(\v2\x18.optimizer.v1.CoordinateR\vdestination\x12)\n" +
	"\x10catalog_revision\x18\x06 \x01(\x03R\x0fcatalogRevision\x122\n" +
	"\x06result\x18\a \x01(\x0e2\x1a.optimizer.v1.ResultStatusR\x06result\x121\n" +
	"\bwarnings\x18\b \x03(\v2\x15.optimizer.v1.WarningR\bwarnings\x124\n" +
	"\tconflicts\x18\t \x03(\v2\x16.optimizer.v1.ConflictR\tconflicts\x12-\n" +
	"\x04cost\x18\n" +
	" \x01(\v2\x19.optimizer.v1.CostSummaryR\x04cost\x124\n" +
	"\bgeometry\x18\v \x03(\v2\x18.optimizer.v1.CoordinateR\bgeometry\x12-\n" +
	"\x05steps\x18\f \x03(\v2\x17.optimizer.v1.RouteStepR\x05steps\x12*\n" +
	"\x04legs\x18\r \x03(\v2\x16.optimizer.v1.RouteLegR\x04legs*\xa2\x01\n" +
	"\fResultStatus\x12\x1d\n" +
	"\x19RESULT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RESULT_STATUS_READY\x10\x01\x12\x19\n" +
	"\x15RESULT_STATUS_PARTIAL\x10\x02\x12#\n" +
	"\x1fRESULT_STATUS_NO_FEASIBLE_ROUTE\x10\x03\x12\x1a\n" +
	"\x16RESULT_STATUS_CONFLICT\x10\x04*\xf1\x01\n" +
	"\x12AvailabilityStatus\x12#\n" +
	"\x1fAVAILABILITY_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAVAILABILITY_STATUS_AVAILABLE\x10\x01\x12-\n" +
	")AVAILABILITY_STATUS_REGISTRATION_REQUIRED\x10\x02\x12 \n" +
	"\x1cAVAILABILITY_STATUS_SOLD_OUT\x10\x03\x12!\n" +
	"\x1dAVAILABILITY_STATUS_CANCELLED\x10\x04\x12\x1f\n" +
	"\x1bAVAILABILITY_STATUS_UNKNOWN\x10\x05*\xbb\x01\n" +
	"\x10BudgetConclusion\x12!\n" +
	"\x1dBUDGET_CONCLUSION_UNSPECIFIED\x10\x00\x12$\n" +
	" BUDGET_CONCLUSION_NOT_APPLICABLE\x10\x01\x12\x1f\n" +
	"\x1bBUDGET_CONCLUSION_SATISFIED\x10\x02\x12\x1e\n" +
	"\x1aBUDGET_CONCLUSION_VIOLATED\x10\x03\x12\x1d\n" +
	"\x19BUDGET_CONCLUSION_UNKNOWN\x10\x04*\xa6\x01\n" +
	"\x15ParticipationEvidence\x12&\n" +
	"\"PARTICIPATION_EVIDENCE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bPARTICIPATION_EVIDENCE_NONE\x10\x01\x12\x1f\n" +
	"\x1bPARTICIPATION_EVIDENCE_USER\x10\x02\x12#\n" +
	"\x1fPARTICIPATION_EVIDENCE_PROVIDER\x10\x03*u\n" +
	"\x12ConstraintStrength\x12#\n" +
	"\x1fCONSTRAINT_STRENGTH_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONSTRAINT_STRENGTH_HARD\x10\x01\x12\x1c\n" +
	"\x18CONSTRAINT_STRENGTH_SOFT\x10\x02*}\n" +
	"\x11ConstraintOutcome\x12\"\n" +
	"\x1eCONSTRAINT_OUTCOME_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONSTRAINT_OUTCOME_SATISFIED\x10\x01\x12\"\n" +
	"\x1eCONSTRAINT_OUTCOME_CONDITIONAL\x10\x02*W\n" +
	"\tVisitKind\x12\x1a\n" +
	"\x16VISIT_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VISIT_KIND_VISIT\x10\x01\x12\x18\n" +
	"\x14VISIT_KIND_FREE_TIME\x10\x02*\x92\x01\n" +
	"\x0fLegEndpointKind\x12!\n" +
	"\x1dLEG_ENDPOINT_KIND_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18LEG_ENDPOINT_KIND_ORIGIN\x10\x01\x12\x1b\n" +
	"\x17LEG_ENDPOINT_KIND_VISIT\x10\x02\x12!\n" +
	"\x1dLEG_ENDPOINT_KIND_DESTINATION\x10\x03*q\n" +
	"\vTargetScope\x12\x1c\n" +
	"\x18TARGET_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TARGET_SCOPE_ROUTE\x10\x01\x12\x16\n" +
	"\x12TARGET_SCOPE_VISIT\x10\x02\x12\x14\n" +
	"\x10TARGET_SCOPE_LEG\x10\x03BBZ@github.com/andres1m/impuls-goroda/proto/optimizer/v1;optimizerv1b\x06proto3"

var (
	file_optimizer_v1_plan_proto_rawDescOnce sync.Once
	file_optimizer_v1_plan_proto_rawDescData []byte
)

func file_optimizer_v1_plan_proto_rawDescGZIP() []byte {
	file_optimizer_v1_plan_proto_rawDescOnce.Do(func() {
		file_optimizer_v1_plan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_v1_plan_proto_rawDesc), len(file_optimizer_v1_plan_proto_rawDesc)))
	})
	return file_optimizer_v1_plan_proto_rawDescData
}

var file_optimizer_v1_plan_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_optimizer_v1_plan_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_optimizer_v1_plan_proto_goTypes = []any{
	(ResultStatus)(0),             // 0: optimizer.v1.ResultStatus
	(AvailabilityStatus)(0),       // 1: optimizer.v1.AvailabilityStatus
	(BudgetConclusion)(0),         // 2: optimizer.v1.BudgetConclusion
	(ParticipationEvidence)(0),    // 3: optimizer.v1.ParticipationEvidence
	(ConstraintStrength)(0),       // 4: optimizer.v1.ConstraintStrength
	(ConstraintOutcome)(0),        // 5: optimizer.v1.ConstraintOutcome
	(VisitKind)(0),                // 6: optimizer.v1.VisitKind
	(LegEndpointKind)(0),          // 7: optimizer.v1.LegEndpointKind
	(TargetScope)(0),              // 8: optimizer.v1.TargetScope
	(*CatalogSnapshot)(nil),       // 9: optimizer.v1.CatalogSnapshot
	(*UnknownCostComponent)(nil),  // 10: optimizer.v1.UnknownCostComponent
	(*CostSnapshot)(nil),          // 11: optimizer.v1.CostSnapshot
	(*CostSummary)(nil),           // 12: optimizer.v1.CostSummary
	(*ParticipationSnapshot)(nil), // 13: optimizer.v1.ParticipationSnapshot
	(*AppliedConstraint)(nil),     // 14: optimizer.v1.AppliedConstraint
	(*RouteStep)(nil),             // 15: optimizer.v1.RouteStep
	(*LegEvidence)(nil),           // 16: optimizer.v1.LegEvidence
	(*RouteLeg)(nil),              // 17: optimizer.v1.RouteLeg
	(*Warning)(nil),               // 18: optimizer.v1.Warning
	(*Conflict)(nil),              // 19: optimizer.v1.Conflict
	(*RoutePlan)(nil),             // 20: optimizer.v1.RoutePlan
	(Category)(0),                 // 21: optimizer.v1.Category
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(DataMode)(0),                 // 23: optimizer.v1.DataMode
	(*Provenance)(nil),            // 24: optimizer.v1.Provenance
	(*Price)(nil),                 // 25: optimizer.v1.Price
	(*Money)(nil),                 // 26: optimizer.v1.Money
	(ParticipationStatus)(0),      // 27: optimizer.v1.ParticipationStatus
	(*Coordinate)(nil),            // 28: optimizer.v1.Coordinate
	(VerificationStatus)(0),       // 29: optimizer.v1.VerificationStatus
	(Archetype)(0),                // 30: optimizer.v1.Archetype
}
var file_optimizer_v1_plan_proto_depIdxs = []int32{
	21, // 0: optimizer.v1.CatalogSnapshot.category:type_name -> optimizer.v1.Category
	1,  // 1: optimizer.v1.CatalogSnapshot.availability:type_name -> optimizer.v1.AvailabilityStatus
	22, // 2: optimizer.v1.CatalogSnapshot.session_starts_at:type_name -> google.protobuf.Timestamp
	22, // 3: optimizer.v1.CatalogSnapshot.session_ends_at:type_name -> google.protobuf.Timestamp
	23, // 4: optimizer.v1.CatalogSnapshot.data_mode:type_name -> optimizer.v1.DataMode
	24, // 5: optimizer.v1.CatalogSnapshot.provenance:type_name -> optimizer.v1.Provenance
	25, // 6: optimizer.v1.CostSnapshot.price:type_name -> optimizer.v1.Price
	26, // 7: optimizer.v1.CostSnapshot.personal_amount:type_name -> optimizer.v1.Money
	26, // 8: optimizer.v1.CostSnapshot.program_amount:type_name -> optimizer.v1.Money
	10, // 9: optimizer.v1.CostSnapshot.unknown_components:type_name -> optimizer.v1.UnknownCostComponent
	24, // 10: optimizer.v1.CostSnapshot.provenance:type_name -> optimizer.v1.Provenance
	26, // 11: optimizer.v1.CostSummary.known_personal:type_name -> optimizer.v1.Money
	26, // 12: optimizer.v1.CostSummary.known_transport:type_name -> optimizer.v1.Money
	26, // 13: optimizer.v1.CostSummary.program_amount:type_name -> optimizer.v1.Money
	26, // 14: optimizer.v1.CostSummary.total_lower:type_name -> optimizer.v1.Money
	26, // 15: optimizer.v1.CostSummary.total_upper:type_name -> optimizer.v1.Money
	10, // 16: optimizer.v1.CostSummary.unknown_components:type_name -> optimizer.v1.UnknownCostComponent
	2,  // 17: optimizer.v1.CostSummary.budget_conclusion:type_name -> optimizer.v1.BudgetConclusion
	27, // 18: optimizer.v1.ParticipationSnapshot.status:type_name -> optimizer.v1.ParticipationStatus
	3,  // 19: optimizer.v1.ParticipationSnapshot.evidence:type_name -> optimizer.v1.ParticipationEvidence
	4,  // 20: optimizer.v1.AppliedConstraint.strength:type_name -> optimizer.v1.ConstraintStrength
	5,  // 21: optimizer.v1.AppliedConstraint.outcome:type_name -> optimizer.v1.ConstraintOutcome
	6,  // 22: optimizer.v1.RouteStep.kind:type_name -> optimizer.v1.VisitKind
	22, // 23: optimizer.v1.RouteStep.arrival_at:type_name -> google.protobuf.Timestamp
	22, // 24: optimizer.v1.RouteStep.visit_start_at:type_name -> google.protobuf.Timestamp
	22, // 25: optimizer.v1.RouteStep.visit_end_at:type_name -> google.protobuf.Timestamp
	22, // 26: optimizer.v1.RouteStep.departure_at:type_name -> google.protobuf.Timestamp
	13, // 27: optimizer.v1.RouteStep.participation:type_name -> optimizer.v1.ParticipationSnapshot
	9,  // 28: optimizer.v1.RouteStep.catalog:type_name -> optimizer.v1.CatalogSnapshot
	11, // 29: optimizer.v1.RouteStep.cost:type_name -> optimizer.v1.CostSnapshot
	14, // 30: optimizer.v1.RouteStep.applied_constraints:type_name -> optimizer.v1.AppliedConstraint
	22, // 31: optimizer.v1.LegEvidence.observed_at:type_name -> google.protobuf.Timestamp
	7,  // 32: optimizer.v1.RouteLeg.from_kind:type_name -> optimizer.v1.LegEndpointKind
	7,  // 33: optimizer.v1.RouteLeg.to_kind:type_name -> optimizer.v1.LegEndpointKind
	22, // 34: optimizer.v1.RouteLeg.departure_at:type_name -> google.protobuf.Timestamp
	22, // 35: optimizer.v1.RouteLeg.arrival_at:type_name -> google.protobuf.Timestamp
	28, // 36: optimizer.v1.RouteLeg.geometry:type_name -> optimizer.v1.Coordinate
	29, // 37: optimizer.v1.RouteLeg.verification:type_name -> optimizer.v1.VerificationStatus
	16, // 38: optimizer.v1.RouteLeg.evidence:type_name -> optimizer.v1.LegEvidence
	11, // 39: optimizer.v1.RouteLeg.cost:type_name -> optimizer.v1.CostSnapshot
	8,  // 40: optimizer.v1.Warning.scope:type_name -> optimizer.v1.TargetScope
	30, // 41: optimizer.v1.RoutePlan.archetype:type_name -> optimizer.v1.Archetype
	22, // 42: optimizer.v1.RoutePlan.start_at:type_name -> google.protobuf.Timestamp
	22, // 43: optimizer.v1.RoutePlan.end_at:type_name -> google.protobuf.Timestamp
	28, // 44: optimizer.v1.RoutePlan.origin:type_name -> optimizer.v1.Coordinate
	28, // 45: optimizer.v1.RoutePlan.destination:type_name -> optimizer.v1.Coordinate
	0,  // 46: optimizer.v1.RoutePlan.result:type_name -> optimizer.v1.ResultStatus
	18, // 47: optimizer.v1.RoutePlan.warnings:type_name -> optimizer.v1.Warning
	19, // 48: optimizer.v1.RoutePlan.conflicts:type_name -> optimizer.v1.Conflict
	12, // 49: optimizer.v1.RoutePlan.cost:type_name -> optimizer.v1.CostSummary
	28, // 50: optimizer.v1.RoutePlan.geometry:type_name -> optimizer.v1.Coordinate
	15, // 51: optimizer.v1.RoutePlan.steps:type_name -> optimizer.v1.RouteStep
	17, // 52: optimizer.v1.RoutePlan.legs:type_name -> optimizer.v1.RouteLeg
	53, // [53:53] is the sub-list for method output_type
	53, // [53:53] is the sub-list for method input_type
	53, // [53:53] is the sub-list for extension type_name
	53, // [53:53] is the sub-list for extension extendee
	0,  // [0:53] is the sub-list for field type_name
}

func init() { file_optimizer_v1_plan_proto_init() }
func file_optimizer_v1_plan_proto_init() {
	if File_optimizer_v1_plan_proto != nil {
		return
	}
	file_optimizer_v1_values_proto_init()
	file_optimizer_v1_plan_proto_msgTypes[8].OneofWrappers = []any{}
	file_optimizer_v1_plan_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_v1_plan_proto_rawDesc), len(file_optimizer_v1_plan_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optimizer_v1_plan_proto_goTypes,
		DependencyIndexes: file_optimizer_v1_plan_proto_depIdxs,
		EnumInfos:         file_optimizer_v1_plan_proto_enumTypes,
		MessageInfos:      file_optimizer_v1_plan_proto_msgTypes,
	}.Build()
	File_optimizer_v1_plan_proto = out.File
	file_optimizer_v1_plan_proto_goTypes = nil
	file_optimizer_v1_plan_proto_depIdxs = nil
}
