// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: optimizer/v1/values.proto

package optimizerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceStatus int32

const (
	PriceStatus_PRICE_STATUS_UNSPECIFIED PriceStatus = 0
	PriceStatus_PRICE_STATUS_FREE        PriceStatus = 1
	PriceStatus_PRICE_STATUS_FIXED       PriceStatus = 2
	PriceStatus_PRICE_STATUS_RANGE       PriceStatus = 3
	// Bounds are absent; an unknown price is never treated as zero.
	PriceStatus_PRICE_STATUS_UNKNOWN PriceStatus = 4
)

// Enum value maps for PriceStatus.
var (
	PriceStatus_name = map[int32]string{
		0: "PRICE_STATUS_UNSPECIFIED",
		1: "PRICE_STATUS_FREE",
		2: "PRICE_STATUS_FIXED",
		3: "PRICE_STATUS_RANGE",
		4: "PRICE_STATUS_UNKNOWN",
	}
	PriceStatus_value = map[string]int32{
		"PRICE_STATUS_UNSPECIFIED": 0,
		"PRICE_STATUS_FREE":        1,
		"PRICE_STATUS_FIXED":       2,
		"PRICE_STATUS_RANGE":       3,
		"PRICE_STATUS_UNKNOWN":     4,
	}
)

func (x PriceStatus) Enum() *PriceStatus {
	p := new(PriceStatus)
	*p = x
	return p
}

func (x PriceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PriceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_values_proto_enumTypes[0].Descriptor()
}

func (PriceStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_values_proto_enumTypes[0]
}

func (x PriceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PriceStatus.Descriptor instead.
func (PriceStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{0}
}

type DataMode int32

const (
	DataMode_DATA_MODE_UNSPECIFIED DataMode = 0
	DataMode_DATA_MODE_LIVE        DataMode = 1
	DataMode_DATA_MODE_PREPARED    DataMode = 2
	DataMode_DATA_MODE_SYNTHETIC   DataMode = 3
)

// Enum value maps for DataMode.
var (
	DataMode_name = map[int32]string{
		0: "DATA_MODE_UNSPECIFIED",
		1: "DATA_MODE_LIVE",
		2: "DATA_MODE_PREPARED",
		3: "DATA_MODE_SYNTHETIC",
	}
	DataMode_value = map[string]int32{
		"DATA_MODE_UNSPECIFIED": 0,
		"DATA_MODE_LIVE":        1,
		"DATA_MODE_PREPARED":    2,
		"DATA_MODE_SYNTHETIC":   3,
	}
)

func (x DataMode) Enum() *DataMode {
	p := new(DataMode)
	*p = x
	return p
}

func (x DataMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataMode) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_values_proto_enumTypes[1].Descriptor()
}

func (DataMode) Type() protoreflect.EnumType {
	return &file_optimizer_v1_values_proto_enumTypes[1]
}

func (x DataMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataMode.Descriptor instead.
func (DataMode) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{1}
}

type Category int32

const (
	Category_CATEGORY_UNSPECIFIED Category = 0
	Category_CATEGORY_CULTURE     Category = 1
	Category_CATEGORY_SPORT       Category = 2
	Category_CATEGORY_VOLUNTEER   Category = 3
	Category_CATEGORY_WALK        Category = 4
	Category_CATEGORY_TOURISM     Category = 5
	Category_CATEGORY_GASTRO      Category = 6
)

// Enum value maps for Category.
var (
	Category_name = map[int32]string{
		0: "CATEGORY_UNSPECIFIED",
		1: "CATEGORY_CULTURE",
		2: "CATEGORY_SPORT",
		3: "CATEGORY_VOLUNTEER",
		4: "CATEGORY_WALK",
		5: "CATEGORY_TOURISM",
		6: "CATEGORY_GASTRO",
	}
	Category_value = map[string]int32{
		"CATEGORY_UNSPECIFIED": 0,
		"CATEGORY_CULTURE":     1,
		"CATEGORY_SPORT":       2,
		"CATEGORY_VOLUNTEER":   3,
		"CATEGORY_WALK":        4,
		"CATEGORY_TOURISM":     5,
		"CATEGORY_GASTRO":      6,
	}
)

func (x Category) Enum() *Category {
	p := new(Category)
	*p = x
	return p
}

func (x Category) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Category) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_values_proto_enumTypes[2].Descriptor()
}

func (Category) Type() protoreflect.EnumType {
	return &file_optimizer_v1_values_proto_enumTypes[2]
}

func (x Category) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Category.Descriptor instead.
func (Category) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{2}
}

type Archetype int32

const (
	Archetype_ARCHETYPE_UNSPECIFIED      Archetype = 0
	Archetype_ARCHETYPE_URBAN_AVANTGARDE Archetype = 1
	Archetype_ARCHETYPE_HISTORY_HERITAGE Archetype = 2
	Archetype_ARCHETYPE_ACTION_SOCIAL    Archetype = 3
)

// Enum value maps for Archetype.
var (
	Archetype_name = map[int32]string{
		0: "ARCHETYPE_UNSPECIFIED",
		1: "ARCHETYPE_URBAN_AVANTGARDE",
		2: "ARCHETYPE_HISTORY_HERITAGE",
		3: "ARCHETYPE_ACTION_SOCIAL",
	}
	Archetype_value = map[string]int32{
		"ARCHETYPE_UNSPECIFIED":      0,
		"ARCHETYPE_URBAN_AVANTGARDE": 1,
		"ARCHETYPE_HISTORY_HERITAGE": 2,
		"ARCHETYPE_ACTION_SOCIAL":    3,
	}
)

func (x Archetype) Enum() *Archetype {
	p := new(Archetype)
	*p = x
	return p
}

func (x Archetype) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Archetype) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_values_proto_enumTypes[3].Descriptor()
}

func (Archetype) Type() protoreflect.EnumType {
	return &file_optimizer_v1_values_proto_enumTypes[3]
}

func (x Archetype) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Archetype.Descriptor instead.
func (Archetype) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{3}
}

type ParticipationStatus int32

const (
	ParticipationStatus_PARTICIPATION_STATUS_UNSPECIFIED             ParticipationStatus = 0
	ParticipationStatus_PARTICIPATION_STATUS_NOT_REQUIRED            ParticipationStatus = 1
	ParticipationStatus_PARTICIPATION_STATUS_ACTION_REQUIRED         ParticipationStatus = 2
	ParticipationStatus_PARTICIPATION_STATUS_USER_REPORTED_CONFIRMED ParticipationStatus = 3
	ParticipationStatus_PARTICIPATION_STATUS_PROVIDER_CONFIRMED      ParticipationStatus = 4
	ParticipationStatus_PARTICIPATION_STATUS_UNAVAILABLE             ParticipationStatus = 5
)

// Enum value maps for ParticipationStatus.
var (
	ParticipationStatus_name = map[int32]string{
		0: "PARTICIPATION_STATUS_UNSPECIFIED",
		1: "PARTICIPATION_STATUS_NOT_REQUIRED",
		2: "PARTICIPATION_STATUS_ACTION_REQUIRED",
		3: "PARTICIPATION_STATUS_USER_REPORTED_CONFIRMED",
		4: "PARTICIPATION_STATUS_PROVIDER_CONFIRMED",
		5: "PARTICIPATION_STATUS_UNAVAILABLE",
	}
	ParticipationStatus_value = map[string]int32{
		"PARTICIPATION_STATUS_UNSPECIFIED":             0,
		"PARTICIPATION_STATUS_NOT_REQUIRED":            1,
		"PARTICIPATION_STATUS_ACTION_REQUIRED":         2,
		"PARTICIPATION_STATUS_USER_REPORTED_CONFIRMED": 3,
		"PARTICIPATION_STATUS_PROVIDER_CONFIRMED":      4,
		"PARTICIPATION_STATUS_UNAVAILABLE":             5,
	}
)

func (x ParticipationStatus) Enum() *ParticipationStatus {
	p := new(ParticipationStatus)
	*p = x
	return p
}

func (x ParticipationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParticipationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_values_proto_enumTypes[4].Descriptor()
}

func (ParticipationStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_values_proto_enumTypes[4]
}

func (x ParticipationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParticipationStatus.Descriptor instead.
func (ParticipationStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{4}
}

type VerificationStatus int32

const (
	VerificationStatus_VERIFICATION_STATUS_UNSPECIFIED VerificationStatus = 0
	VerificationStatus_VERIFICATION_STATUS_VERIFIED    VerificationStatus = 1
	VerificationStatus_VERIFICATION_STATUS_ESTIMATED   VerificationStatus = 2
	VerificationStatus_VERIFICATION_STATUS_UNKNOWN     VerificationStatus = 3
	VerificationStatus_VERIFICATION_STATUS_UNAVAILABLE VerificationStatus = 4
)

// Enum value maps for VerificationStatus.
var (
	VerificationStatus_name = map[int32]string{
		0: "VERIFICATION_STATUS_UNSPECIFIED",
		1: "VERIFICATION_STATUS_VERIFIED",
		2: "VERIFICATION_STATUS_ESTIMATED",
		3: "VERIFICATION_STATUS_UNKNOWN",
		4: "VERIFICATION_STATUS_UNAVAILABLE",
	}
	VerificationStatus_value = map[string]int32{
		"VERIFICATION_STATUS_UNSPECIFIED": 0,
		"VERIFICATION_STATUS_VERIFIED":    1,
		"VERIFICATION_STATUS_ESTIMATED":   2,
		"VERIFICATION_STATUS_UNKNOWN":     3,
		"VERIFICATION_STATUS_UNAVAILABLE": 4,
	}
)

func (x VerificationStatus) Enum() *VerificationStatus {
	p := new(VerificationStatus)
	*p = x
	return p
}

func (x VerificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VerificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_optimizer_v1_values_proto_enumTypes[5].Descriptor()
}

func (VerificationStatus) Type() protoreflect.EnumType {
	return &file_optimizer_v1_values_proto_enumTypes[5]
}

func (x VerificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VerificationStatus.Descriptor instead.
func (VerificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{5}
}

type Coordinate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	mi := &file_optimizer_v1_values_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_values_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{0}
}

func (x *Coordinate) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

// Amounts are integer minor units of an ISO 4217 currency. A known zero is a real amount.
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountMinor   int64                  `protobuf:"varint,1,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_optimizer_v1_values_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_values_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{1}
}

func (x *Money) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PriceStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=optimizer.v1.PriceStatus" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	LowerMinor    *int64                 `protobuf:"varint,3,opt,name=lower_minor,json=lowerMinor,proto3,oneof" json:"lower_minor,omitempty"`
	UpperMinor    *int64                 `protobuf:"varint,4,opt,name=upper_minor,json=upperMinor,proto3,oneof" json:"upper_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_optimizer_v1_values_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_values_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{2}
}

func (x *Price) GetStatus() PriceStatus {
	if x != nil {
		return x.Status
	}
	return PriceStatus_PRICE_STATUS_UNSPECIFIED
}

func (x *Price) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Price) GetLowerMinor() int64 {
	if x != nil && x.LowerMinor != nil {
		return *x.LowerMinor
	}
	return 0
}

func (x *Price) GetUpperMinor() int64 {
	if x != nil && x.UpperMinor != nil {
		return *x.UpperMinor
	}
	return 0
}

// Origin of a catalog fact. A missing source update time is never replaced by the fetch time.
type Provenance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceName      string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceUrl       *string                `protobuf:"bytes,2,opt,name=source_url,json=sourceUrl,proto3,oneof" json:"source_url,omitempty"`
	SourceRecordId  []byte                 `protobuf:"bytes,3,opt,name=source_record_id,json=sourceRecordId,proto3" json:"source_record_id,omitempty"`
	SourceUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=source_updated_at,json=sourceUpdatedAt,proto3" json:"source_updated_at,omitempty"`
	FetchedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fetched_at,json=fetchedAt,proto3" json:"fetched_at,omitempty"`
	VerifiedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_optimizer_v1_values_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_values_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{3}
}

func (x *Provenance) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Provenance) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

func (x *Provenance) GetSourceRecordId() []byte {
	if x != nil {
		return x.SourceRecordId
	}
	return nil
}

func (x *Provenance) GetSourceUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceUpdatedAt
	}
	return nil
}

func (x *Provenance) GetFetchedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FetchedAt
	}
	return nil
}

func (x *Provenance) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

type DataFreshness struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The weakest mode among the facts used in the result.
	DataMode        DataMode               `protobuf:"varint,1,opt,name=data_mode,json=dataMode,proto3,enum=optimizer.v1.DataMode" json:"data_mode,omitempty"`
	DataAsOf        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=data_as_of,json=dataAsOf,proto3" json:"data_as_of,omitempty"`
	CatalogRevision int64                  `protobuf:"varint,3,opt,name=catalog_revision,json=catalogRevision,proto3" json:"catalog_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DataFreshness) Reset() {
	*x = DataFreshness{}
	mi := &file_optimizer_v1_values_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFreshness) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFreshness) ProtoMessage() {}

func (x *DataFreshness) ProtoReflect() protoreflect.Message {
	mi := &file_optimizer_v1_values_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFreshness.ProtoReflect.Descriptor instead.
func (*DataFreshness) Descriptor() ([]byte, []int) {
	return file_optimizer_v1_values_proto_rawDescGZIP(), []int{4}
}

func (x *DataFreshness) GetDataMode() DataMode {
	if x != nil {
		return x.DataMode
	}
	return DataMode_DATA_MODE_UNSPECIFIED
}

func (x *DataFreshness) GetDataAsOf() *timestamppb.Timestamp {
	if x != nil {
		return x.DataAsOf
	}
	return nil
}

func (x *DataFreshness) GetCatalogRevision() int64 {
	if x != nil {
		return x.CatalogRevision
	}
	return 0
}

var File_optimizer_v1_values_proto protoreflect.FileDescriptor

const file_optimizer_v1_values_proto_rawDesc = "" +
	"\n" +
	"\x19optimizer/v1/values.proto\x12\foptimizer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\n" +
	"Coordinate\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"F\n" +
	"\x05Money\x12!\n" +
	"\famount_minor\x18\x01 \x01(\x03R\vamountMinor\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\xc2\x01\n" +
	"\x05Price\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.optimizer.v1.PriceStatusR\x06status\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12$\n" +
	"\vlower_minor\x18\x03 \x01(\x03H\x00R\n" +
	"lowerMinor\x88\x01\x01\x12$\n" +
	"\vupper_minor\x18\x04 \x01(\x03H\x01R\n" +
	"upperMinor\x88\x01\x01B\x0e\n" +
	"\f_lower_minorB\x0e\n" +
	"\f_upper_minor\"\xca\x02\n" +
	"\n" +
	"Provenance\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12\"\n" +
	"\n" +
	"source_url\x18\x02 \x01(\tH\x00R\tsourceUrl\x88\x01\x01\x12(\n" +
	"\x10source_record_id\x18\x03 \x01(\fR\x0esourceRecordId\x12F\n" +
	"\x11source_updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0fsourceUpdatedAt\x129\n" +
	"\n" +
	"fetched_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tfetchedAt\x12;\n" +
	"\vverified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAtB\r\n" +
	"\v_source_url\"\xa9\x01\n" +
	"\rDataFreshness\x123\n" +
	"\tdata_mode\x18\x01 \x01(\x0e2\x16.optimizer.v1.DataModeR\bdataMode\x128\n" +
	"\n" +
	"data_as_of\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdataAsOf\x12)\n" +
	"\x10catalog_revision\x18\x03 \x01(\x03R\x0fcatalogRevision*\x8c\x01\n" +
	"\vPriceStatus\x12\x1c\n" +
	"\x18PRICE_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11PRICE_STATUS_FREE\x10\x01\x12\x16\n" +
	"\x12PRICE_STATUS_FIXED\x10\x02\x12\x16\n" +
	"\x12PRICE_STATUS_RANGE\x10\x03\x12\x18\n" +
	"\x14PRICE_STATUS_UNKNOWN\x10\x04*j\n" +
	"\bDataMode\x12\x19\n" +
	"\x15DATA_MODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDATA_MODE_LIVE\x10\x01\x12\x16\n" +
	"\x12DATA_MODE_PREPARED\x10\x02\x12\x17\n" +
	"\x13DATA_MODE_SYNTHETIC\x10\x03*\xa4\x01\n" +
	"\bCategory\x12\x18\n" +
	"\x14CATEGORY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CATEGORY_CULTURE\x10\x01\x12\x12\n" +
	"\x0eCATEGORY_SPORT\x10\x02\x12\x16\n" +
	"\x12CATEGORY_VOLUNTEER\x10\x03\x12\x11\n" +
	"\rCATEGORY_WALK\x10\x04\x12\x14\n" +
	"\x10CATEGORY_TOURISM\x10\x05\x12\x13\n" +
	"\x0fCATEGORY_GASTRO\x10\x06*\x83\x01\n" +
	"\tArchetype\x12\x19\n" +
	"\x15ARCHETYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aARCHETYPE_URBAN_AVANTGARDE\x10\x01\x12\x1e\n" +
	"\x1aARCHETYPE_HISTORY_HERITAGE\x10\x02\x12\x1b\n" +
	"\x17ARCHETYPE_ACTION_SOCIAL\x10\x03*\x91\x02\n" +
	"\x13ParticipationStatus\x12$\n" +
	" PARTICIPATION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!PARTICIPATION_STATUS_NOT_REQUIRED\x10\x01\x12(\n" +
	"$PARTICIPATION_STATUS_ACTION_REQUIRED\x10\x02\x120\n" +
	",PARTICIPATION_STATUS_USER_REPORTED_CONFIRMED\x10\x03\x12+\n" +
	"'PARTICIPATION_STATUS_PROVIDER_CONFIRMED\x10\x04\x12$\n" +
	" PARTICIPATION_STATUS_UNAVAILABLE\x10\x05*\xc4\x01\n" +
	"\x12VerificationStatus\x12#\n" +
	"\x1fVERIFICATION_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cVERIFICATION_STATUS_VERIFIED\x10\x01\x12!\n" +
	"\x1dVERIFICATION_STATUS_ESTIMATED\x10\x02\x12\x1f\n" +
	"\x1bVERIFICATION_STATUS_UNKNOWN\x10\x03\x12#\n" +
	"\x1fVERIFICATION_STATUS_UNAVAILABLE\x10\x04BBZ@github.com/andres1m/impuls-goroda/proto/optimizer/v1;optimizerv1b\x06proto3"

var (
	file_optimizer_v1_values_proto_rawDescOnce sync.Once
	file_optimizer_v1_values_proto_rawDescData []byte
)

func file_optimizer_v1_values_proto_rawDescGZIP() []byte {
	file_optimizer_v1_values_proto_rawDescOnce.Do(func() {
		file_optimizer_v1_values_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizer_v1_values_proto_rawDesc), len(file_optimizer_v1_values_proto_rawDesc)))
	})
	return file_optimizer_v1_values_proto_rawDescData
}

var file_optimizer_v1_values_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_optimizer_v1_values_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_optimizer_v1_values_proto_goTypes = []any{
	(PriceStatus)(0),              // 0: optimizer.v1.PriceStatus
	(DataMode)(0),                 // 1: optimizer.v1.DataMode
	(Category)(0),                 // 2: optimizer.v1.Category
	(Archetype)(0),                // 3: optimizer.v1.Archetype
	(ParticipationStatus)(0),      // 4: optimizer.v1.ParticipationStatus
	(VerificationStatus)(0),       // 5: optimizer.v1.VerificationStatus
	(*Coordinate)(nil),            // 6: optimizer.v1.Coordinate
	(*Money)(nil),                 // 7: optimizer.v1.Money
	(*Price)(nil),                 // 8: optimizer.v1.Price
	(*Provenance)(nil),            // 9: optimizer.v1.Provenance
	(*DataFreshness)(nil),         // 10: optimizer.v1.DataFreshness
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_optimizer_v1_values_proto_depIdxs = []int32{
	0,  // 0: optimizer.v1.Price.status:type_name -> optimizer.v1.PriceStatus
	11, // 1: optimizer.v1.Provenance.source_updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: optimizer.v1.Provenance.fetched_at:type_name -> google.protobuf.Timestamp
	11, // 3: optimizer.v1.Provenance.verified_at:type_name -> google.protobuf.Timestamp
	1,  // 4: optimizer.v1.DataFreshness.data_mode:type_name -> optimizer.v1.DataMode
	11, // 5: optimizer.v1.DataFreshness.data_as_of:type_name -> google.protobuf.Timestamp
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_optimizer_v1_values_proto_init() }
func file_optimizer_v1_values_proto_init() {
	if File_optimizer_v1_values_proto != nil {
		return
	}
	file_optimizer_v1_values_proto_msgTypes[2].OneofWrappers = []any{}
	file_optimizer_v1_values_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizer_v1_values_proto_rawDesc), len(file_optimizer_v1_values_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_optimizer_v1_values_proto_goTypes,
		DependencyIndexes: file_optimizer_v1_values_proto_depIdxs,
		EnumInfos:         file_optimizer_v1_values_proto_enumTypes,
		MessageInfos:      file_optimizer_v1_values_proto_msgTypes,
	}.Build()
	File_optimizer_v1_values_proto = out.File
	file_optimizer_v1_values_proto_goTypes = nil
	file_optimizer_v1_values_proto_depIdxs = nil
}
