// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gateway/v1/lifecycle.proto

package gatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverCatalogLifecycleRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion         uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	DeliveryId            []byte                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ChangeId              []byte                 `protobuf:"bytes,3,opt,name=change_id,json=changeId,proto3" json:"change_id,omitempty"`
	City                  string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	CatalogRevision       int64                  `protobuf:"varint,5,opt,name=catalog_revision,json=catalogRevision,proto3" json:"catalog_revision,omitempty"`
	EventId               []byte                 `protobuf:"bytes,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SessionId             []byte                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OldAvailabilityStatus string                 `protobuf:"bytes,8,opt,name=old_availability_status,json=oldAvailabilityStatus,proto3" json:"old_availability_status,omitempty"`
	NewAvailabilityStatus string                 `protobuf:"bytes,9,opt,name=new_availability_status,json=newAvailabilityStatus,proto3" json:"new_availability_status,omitempty"`
	SourceRecordId        string                 `protobuf:"bytes,10,opt,name=source_record_id,json=sourceRecordId,proto3" json:"source_record_id,omitempty"`
	DataMode              string                 `protobuf:"bytes,11,opt,name=data_mode,json=dataMode,proto3" json:"data_mode,omitempty"`
	ObservedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Reason                string                 `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeliverCatalogLifecycleRequest) Reset() {
	*x = DeliverCatalogLifecycleRequest{}
	mi := &file_gateway_v1_lifecycle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverCatalogLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverCatalogLifecycleRequest) ProtoMessage() {}

func (x *DeliverCatalogLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_lifecycle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverCatalogLifecycleRequest.ProtoReflect.Descriptor instead.
func (*DeliverCatalogLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverCatalogLifecycleRequest) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *DeliverCatalogLifecycleRequest) GetDeliveryId() []byte {
	if x != nil {
		return x.DeliveryId
	}
	return nil
}

func (x *DeliverCatalogLifecycleRequest) GetChangeId() []byte {
	if x != nil {
		return x.ChangeId
	}
	return nil
}

func (x *DeliverCatalogLifecycleRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DeliverCatalogLifecycleRequest) GetCatalogRevision() int64 {
	if x != nil {
		return x.CatalogRevision
	}
	return 0
}

func (x *DeliverCatalogLifecycleRequest) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *DeliverCatalogLifecycleRequest) GetSessionId() []byte {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *DeliverCatalogLifecycleRequest) GetOldAvailabilityStatus() string {
	if x != nil {
		return x.OldAvailabilityStatus
	}
	return ""
}

func (x *DeliverCatalogLifecycleRequest) GetNewAvailabilityStatus() string {
	if x != nil {
		return x.NewAvailabilityStatus
	}
	return ""
}

func (x *DeliverCatalogLifecycleRequest) GetSourceRecordId() string {
	if x != nil {
		return x.SourceRecordId
	}
	return ""
}

func (x *DeliverCatalogLifecycleRequest) GetDataMode() string {
	if x != nil {
		return x.DataMode
	}
	return ""
}

func (x *DeliverCatalogLifecycleRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *DeliverCatalogLifecycleRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeliverCatalogLifecycleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    []byte                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverCatalogLifecycleResponse) Reset() {
	*x = DeliverCatalogLifecycleResponse{}
	mi := &file_gateway_v1_lifecycle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverCatalogLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverCatalogLifecycleResponse) ProtoMessage() {}

func (x *DeliverCatalogLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_lifecycle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverCatalogLifecycleResponse.ProtoReflect.Descriptor instead.
func (*DeliverCatalogLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_lifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *DeliverCatalogLifecycleResponse) GetDeliveryId() []byte {
	if x != nil {
		return x.DeliveryId
	}
	return nil
}

var File_gateway_v1_lifecycle_proto protoreflect.FileDescriptor

const file_gateway_v1_lifecycle_proto_rawDesc = "" +
	"\n" +
	"\x1agateway/v1/lifecycle.proto\x12\n" +
	"gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x04\n" +
	"\x1eDeliverCatalogLifecycleRequest\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\fR\n" +
	"deliveryId\x12\x1b\n" +
	"\tchange_id\x18\x03 \x01(\fR\bchangeId\x12\x12\n" +
	"\x04city\x18\x04 \x01(\tR\x04city\x12)\n" +
	"\x10catalog_revision\x18\x05 \x01(\x03R\x0fcatalogRevision\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\fR\aeventId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\fR\tsessionId\x126\n" +
	"\x17old_availability_status\x18\b \x01(\tR\x15oldAvailabilityStatus\x126\n" +
	"\x17new_availability_status\x18\t \x01(\tR\x15newAvailabilityStatus\x12(\n" +
	"\x10source_record_id\x18\n" +
	" \x01(\tR\x0esourceRecordId\x12\x1b\n" +
	"\tdata_mode\x18\v \x01(\tR\bdataMode\x12;\n" +
	"\vobserved_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x16\n" +
	"\x06reason\x18\r \x01(\tR\x06reason\"B\n" +
	"\x1fDeliverCatalogLifecycleResponse\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\fR\n" +
	"deliveryId2\x86\x01\n" +
	"\x10LifecycleService\x12r\n" +
	"\x17DeliverCatalogLifecycle\x12*.gateway.v1.DeliverCatalogLifecycleRequest\x1a+.gateway.v1.DeliverCatalogLifecycleResponseB>Z<github.com/andres1m/impuls-goroda/proto/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_v1_lifecycle_proto_rawDescOnce sync.Once
	file_gateway_v1_lifecycle_proto_rawDescData []byte
)

func file_gateway_v1_lifecycle_proto_rawDescGZIP() []byte {
	file_gateway_v1_lifecycle_proto_rawDescOnce.Do(func() {
		file_gateway_v1_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_lifecycle_proto_rawDesc), len(file_gateway_v1_lifecycle_proto_rawDesc)))
	})
	return file_gateway_v1_lifecycle_proto_rawDescData
}

var file_gateway_v1_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_v1_lifecycle_proto_goTypes = []any{
	(*DeliverCatalogLifecycleRequest)(nil),  // 0: gateway.v1.DeliverCatalogLifecycleRequest
	(*DeliverCatalogLifecycleResponse)(nil), // 1: gateway.v1.DeliverCatalogLifecycleResponse
	(*timestamppb.Timestamp)(nil),           // 2: google.protobuf.Timestamp
}
var file_gateway_v1_lifecycle_proto_depIdxs = []int32{
	2, // 0: gateway.v1.DeliverCatalogLifecycleRequest.observed_at:type_name -> google.protobuf.Timestamp
	0, // 1: gateway.v1.LifecycleService.DeliverCatalogLifecycle:input_type -> gateway.v1.DeliverCatalogLifecycleRequest
	1, // 2: gateway.v1.LifecycleService.DeliverCatalogLifecycle:output_type -> gateway.v1.DeliverCatalogLifecycleResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_v1_lifecycle_proto_init() }
func file_gateway_v1_lifecycle_proto_init() {
	if File_gateway_v1_lifecycle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_lifecycle_proto_rawDesc), len(file_gateway_v1_lifecycle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_lifecycle_proto_goTypes,
		DependencyIndexes: file_gateway_v1_lifecycle_proto_depIdxs,
		MessageInfos:      file_gateway_v1_lifecycle_proto_msgTypes,
	}.Build()
	File_gateway_v1_lifecycle_proto = out.File
	file_gateway_v1_lifecycle_proto_goTypes = nil
	file_gateway_v1_lifecycle_proto_depIdxs = nil
}
